Add windows cpp sample
VOICEVOX/voicevox_core pull request #112
Opened 2022-04-01 16:07 UTC by shigobu

## 内容

Windowsで動くC++用のサンプルコードを追加します。  
Microsoft Visual Studio Community 2022 で作成しています。

core.dllを暗黙的リンクするために、core.libが必要です。
自分のリポジトリでbuild.ymlを編集してlibファイルを作成するようにして使っています。後でPR出します。

出力ディレクトリにcore.dllとOpen JTalk辞書フォルダの配置が必要です。
lib\x64(or Win32)にcore.libを配置する必要があります。

OnnxRuntimeはNuGetで取得します。

## 関連 Issue

https://github.com/VOICEVOX/voicevox_project/issues/1

## その他

2022-04-04 01:11 UTC, shigobu commented
完成したので、レビューをお願いします。

2022-04-05 13:24 UTC, Yosshi999 commented
いまVS2022が手元にないのでとりあえずVS2019 (v142)でビルドしてみましたが、core.dllの序数5が見つからないといわれて実行できませんでした。多分こっちのローカル環境がごちゃごちゃしてるせいなのでもうちょっと調べてみますが、@shigobuさんなにか心当たりありますか？

2022-04-05 15:22 UTC, Oyaki122 commented
> [QUESTION] あとcore.libについてはどうしましょうか。releasesに含めるべき(cc. @Hiroshiba )か [dllからlibを生成するバッチファイル](https://github.com/VOICEVOX/voicevox_core/blob/3eec3d5fc1a6fdbf155834fd1ad145581127f8d5/example/python/makelib.bat) を復活させるか... 動的なロードならlibファイルは要らないんでしたっけ？この選択肢はこういったVC++プロジェクトでもアリなんでしょうか

.libに関しては #111 でRelease対象に含まれるようになったため問題ないと思います

2022-04-06 00:44 UTC, shigobu commented
> いまVS2022が手元にないのでとりあえずVS2019 (v142)でビルドしてみましたが、core.dllの序数5が見つからないといわれて実行できませんでした。多分こっちのローカル環境がごちゃごちゃしてるせいなのでもうちょっと調べてみますが、@shigobuさんなにか心当たりありますか？

initialize関数の定義がRelease（[0.12.0-preview.1](https://github.com/VOICEVOX/voicevox_core/releases/tag/0.12.0-preview.1)）に上がっているものから変更になっています。
DLLにモデルファイルを埋め込んだのでパスを指定する引数が削除されています。
ActionsのArtifactsからダウンロードしたものを使用してください。
https://github.com/VOICEVOX/voicevox_core/actions/runs/2082324805

心当たりがあるといえばこのくらいです。
すでに、Actionsからダウンロードしたものを使用していたらすみません。

2022-04-06 12:14 UTC, shigobu commented
README追加しました。

2022-04-06 13:33 UTC, Yosshi999 commented
> core.dllの序数5が見つからないといわれて実行できませんでした

この件解決しました。core.dllのビルドに使っていたonnxruntimeとsimple_ttsが読み込んでいたonnxruntimeのバージョンが一致していませんでした。

確認ですが、
* 出力ディレクトリに現れるonnxruntime.dllとonnxruntime_providers_shared.dllはNuGetでダウンロードしてきた`Microsoft.ML.OnnxRuntime.1.11.0` であるという認識であってますか？
* 今のvoicevox_coreリポジトリを見る限りcore.dllがリンクするonnxruntimeは1.10.0のはずですが、@shigobuさんの環境ではbin/x64/Debug (or Release) にあるonnxruntime.dllの出所はどうなっていますか？

2022-04-06 13:57 UTC, shigobu commented
> * 出力ディレクトリに現れるonnxruntime.dllとonnxruntime_providers_shared.dllはNuGetでダウンロードしてきた`Microsoft.ML.OnnxRuntime.1.11.0` であるという認識であってますか？

あっています。

> * 今のvoicevox_coreリポジトリを見る限りcore.dllがリンクするonnxruntimeは1.10.0のはずですが、@shigobuさんの環境ではbin/x64/Debug (or Release) にあるonnxruntime.dllの出所はどうなっていますか？

NuGetでダウンロードした`Microsoft.ML.OnnxRuntime.1.11.0`です。
製品版からコピーしたかもと思って、ファイルバージョンを比較してみました。
製品版は1.10で、bin/x64/Debugにあるのは1.11でした。

2022-04-06 14:05 UTC, shigobu commented
私の環境では正常にダミー音声が再生されたので、そのままにしてたのですが、
`Microsoft.ML.OnnxRuntime`のバージョンは、`1.10.0`にしたほうが良さそうですね。

2022-04-06 14:14 UTC, Yosshi999 commented
> Microsoft.ML.OnnxRuntimeのバージョンは、1.10.0に
お願いします 🙇 

将来にわたってこのexampleのバージョンを揃える必要があるので出来ればこのNuGetなしで完結するのがいいんですが、その作業は製品版にDirectMLが同梱されてからでよさそうですかね

2022-04-06 15:18 UTC, Yosshi999 commented
すみません。対応してもらって申し訳ないのですが、versionを揃えてもまだ序数のエラーが出てしまいました。

いまonnxruntime.dllのexportsを確認したところ、python configure.pyで拾ってくるものとNuGetが拾ってくるものが違っているようでした。もう少し調べてみます。

<details> <summary> dumpbin /exports の結果 </summary>

```
Dump of file example\cpp\windows\packages\Microsoft.ML.OnnxRuntime.1.10.0\runtimes\win-x64\native\onnxruntime.dll

File Type: DLL

  Section contains the following exports for onnxruntime.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           2 number of functions
           2 number of names

    ordinal hint RVA      name

          1    0 00018740 OrtGetApiBase = OrtGetApiBase
          2    1 00101630 OrtSessionOptionsAppendExecutionProvider_CPU = OrtSessionOptionsAppendExecutionProvider_CPU

  Summary

       11000 .data
       31000 .pdata
       F8000 .rdata
        7000 .reloc
        1000 .rsrc
      5CB000 .text
        1000 _RDATA

-----------------------------------------------------------------------------
Dump of file onnxruntime\runtimes\win-x64\native\onnxruntime.dll

File Type: DLL

  Section contains the following exports for onnxruntime.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           5 number of functions
           5 number of names

    ordinal hint RVA      name

          1    0 00018BC0 OrtGetApiBase = OrtGetApiBase
          2    1 00133560 OrtGetWinMLAdapter = ?OrtGetWinMLAdapter@@YAPEBUWinmlAdapterApi@@I@Z (struct WinmlAdapterApi const * __cdecl OrtGetWinMLAdapter(unsigned int))
          3    2 0007A8A0 OrtSessionOptionsAppendExecutionProviderEx_DML = OrtSessionOptionsAppendExecutionProviderEx_DML
          4    3 001CE670 OrtSessionOptionsAppendExecutionProvider_CPU = OrtSessionOptionsAppendExecutionProvider_CPU
          5    4 0007A810 OrtSessionOptionsAppendExecutionProvider_DML = OrtSessionOptionsAppendExecutionProvider_DML

  Summary

       49000 .data
        1000 .didat
       39000 .pdata
      17C000 .rdata
        C000 .reloc
        1000 .rsrc
      6A3000 .text
        1000 _RDATA

</details>

2022-04-06 22:26 UTC, Yosshi999 commented
すみませんずっと勘違いしていてDirectML版のcore.dllを使っていました。
cpu版のcore.dllにしたところちゃんと動作することを確認しました

2022-04-07 09:22 UTC, Yosshi999 requested changes
日本語パスでも動作を確認しました！
いくつかコメント残したので対応お願いします。

2022-04-07 09:22 UTC, Yosshi999 commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  result = voicevox_tts(wide_to_utf8_cppapi(speak_words).c_str(), speaker_id, &output_binary_size, &output_wav);
[SHOULD] 現在のcore.dll実装には `voicevox_tts` に長すぎる文字列を与えるとbuffer overflowでクラッシュするというバグが存在するので、入力する文字列のbyte数に制限を与えてほしいです。
https://github.com/VOICEVOX/voicevox_engine/issues/384 ここの議論にあるように2560文字くらいにするのがよさそうです。

[MAY] `voicevox_tts` は `std::runtime` 例外が飛びうる(あと多分bad_allocも)のでcatchしてほしいです。

2022-04-07 09:22 UTC, Yosshi999 commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  if (::_wcstombs_s_l(&converted, dest.data(), dest.size(), src.data(), _TRUNCATE, ::_create_locale(LC_ALL, "jpn")) !=
[QUESTION] これ日本語ロケール以外の環境だとどうなるか知見あります？パスに英語しか含まれていないなら基本どの言語設定でも動くという認識であってますかね

2022-04-07 09:29 UTC, Yosshi999 requested changes

2022-04-07 09:29 UTC, Yosshi999 commented on example/cpp/windows/README.md
> +*マージされたら*
```suggestion
```

https://github.com/VOICEVOX/voicevox_core/pull/111
マージされたので消しちゃいましょう

2022-04-07 09:52 UTC, PickledChair commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  result = voicevox_tts(wide_to_utf8_cppapi(speak_words).c_str(), speaker_id, &output_binary_size, &output_wav);
> これ思ったんですがどっちもcore実装の方を直すべきですかね...

そうだと思います！ #93 の時点で自分も https://github.com/VOICEVOX/voicevox_core/pull/93#issuecomment-1064945185 のように質問したことがあったのですが、例外処理を core 内で完結させる作業は別 PR に分けたほうが良さそうという意見に落ち着き、それ以来これについて特に進捗はない、というステートにある感じな気がします。なのでサンプル側で catch する必要はなくて、今後 core 側での作業が必要そうです。

2022-04-07 11:42 UTC, shigobu commented on example/cpp/windows/README.md
> +*マージされたら*
「マージされるまで」を削除しました。

2022-04-07 11:53 UTC, shigobu commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  if (::_wcstombs_s_l(&converted, dest.data(), dest.size(), src.data(), _TRUNCATE, ::_create_locale(LC_ALL, "jpn")) !=
>パスにasciiしか含まれていないなら基本どの言語設定でも動くという認識であってますかね

マイクロソフトの以下のページには、
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/wcstombs-s-wcstombs-s-l?view=msvc-170
「マルチバイト文字に変換できないワイド文字が検出された場合、wcstombs_s は *ReturnValue に 0 を入れ、コピー先バッファーを空文字列に設定し、errno を EILSEQ に設定して、EILSEQ を返します。」
とあるので、ascii文字しか含まれていなければ、どの言語設定でも動くと思われます。

2022-04-07 11:56 UTC, shigobu commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  result = voicevox_tts(wide_to_utf8_cppapi(speak_words).c_str(), speaker_id, &output_binary_size, &output_wav);
とりあえず、現状維持しときます。

2022-04-08 13:54 UTC, Hiroshiba reviewed
あ、もし余力があれば、サンプルコードがビルドできるかのテストCIをGithub Actionsで回しておくと良いかもとちょっと思いました！
たぶん`cd example/cpp/windows/simple_tts`して`msbuild`をいい感じに実行すればOKかなと･･･！

2022-04-08 14:47 UTC, Oyaki122 requested changes
実装いただきありがとうございます
遅れましたが確認させていただきました

こちらの方で再生に関して問題がありましたが、それ以外に関しては問題ないと思います

再生の件についてはよくわかりませんでした…
とりあえず一旦Request changesにしますが、他の方で同様の事例がなさそうであればApproveします

2022-04-08 14:47 UTC, Oyaki122 commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  PlaySound((LPCTSTR)output_wav, nullptr, SND_MEMORY);
私の環境固有のものだと思いますが、PlaySound関数で音声を再生することができませんでした
wavファイル出力したところ正しく合成できていたため、再生側の問題だと思われます

こちらの環境はWindows11 21H2です

調べたところ一件だけ似たような症状の記事を見つけました
https://talk.inasoft.org/20211108-0000.html

私のような環境が他にもある場合には、wavファイルでの出力を検討したほうがいいかもしれません

2022-04-11 00:59 UTC, Hiroshiba commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  PlaySound((LPCTSTR)output_wav, nullptr, SND_MEMORY);
サンプルちょっと眺めさせていただきました。
とても丁寧な良いサンプルコードだと感じました！！

@Oyaki122 さんのコメントを見て感じたことをコメントしたいと思います。

実際にこのコアを使いたいニーズは、音声を再生したい・音声ファイルを保存したいという２つがあると思います。
可能であればどちらも実装すると喜ばれそうに感じました！

2022-04-11 04:15 UTC, shigobu commented
> あ、もし余力があれば、サンプルコードがビルドできるかのテストCIをGithub Actionsで回しておくと良いかもとちょっと思いました！ たぶん`cd example/cpp/windows/simple_tts`して`msbuild`をいい感じに実行すればOKかなと･･･！

build.ymlにjobを追加する形で良いでしょうか？
ビルドする時にcore.libが必要なので、どこからか持ってくる必要があります。build.ymlの中でcore.dllのビルド後に実行するのが簡単だと思いました。

私のリポジトリでブランチ分けて試しに作ってみたところ、ビルドに成功しました。

2022-04-11 22:35 UTC, Hiroshiba commented
> build.ymlにjobを追加する形で良いでしょうか？

良いと思います！！
releaseにuploadする前にエラーになるとリリース作業に支障が出てしまうので、そのあとに実行される形だと利便性が損なわれず嬉しそうです！

2022-04-12 02:41 UTC, shigobu commented
build.ymlに、サンプルコードをビルドするjobを追加しました。
`needs: [build-cpp-shared]`を指定しているので、リリースにアップロードするjobと並列で動くはずです。

2022-04-12 13:11 UTC, Oyaki122 approved these changes
LGTM!

2022-04-14 01:39 UTC, merged