static castやnullopt比較をやめ、has_value/value関数を使うようにする
VOICEVOX/voicevox_core pull request #118
Opened 2022-04-20 02:48 UTC by y-chan

## 内容

最初コードを書いていたときに、`has_value`/`value`関数を知らず、後から知って、こちらの方がコードが綺麗になることがわかったので、リファクタリングとして変更しました。

2022-04-20 18:06 UTC, Oyaki122 requested changes
PRありがとうございます
とても見やすくなったと思います

一つ確認なのですが、synthesis_engine.cpp 207行目などの、同じ変数でhas_value()に変更している箇所があるにもかかわらず、std::nulloptとの比較から変更していない部分については、どのように可読性が悪いと思いましたか？
確かに変数名が長いものに関しては==で区切りがあったほうが可読性が高いと思います
ただこの箇所などについては個人的にあまり可読性が悪いと感じなかったため、問題なければ統一したほうがいいのではないでしょうか

お手数をおかけしますがよろしくお願いします

2022-04-20 18:30 UTC, PickledChair commented
C++ の optional に有効値/無効値が入っていることを判定する一般的なやり方について調べてみたのですが、

```c++
std::optional<SomeType> opt_var = get_opt_sometype();

// 有効値が入っていることの確認
if (opt_var) {
  // 中身を取り出す
  SomeType value = opt_var.value();
  ...
}

// 無効値が入っていることの確認
if (!opt_var) {
  ...
}
```

というような方法が最も簡潔そうだったので、提案してみます。

参考： https://cpprefjp.github.io/reference/optional/optional.html

2022-04-20 21:57 UTC, y-chan commented
> synthesis_engine.cpp 207行目など

おっと、これは単純に見落としていたようです。

> optional に有効値/無効値が入っていることを判定するやり方について調べてみた

確かに、こちらの方がきれいそうです...!
せっかくなのでこちらの手法に変更してみようかなと思います...!

2022-04-21 14:56 UTC, Yosshi999 requested changes

2022-04-21 14:56 UTC, Yosshi999 commented on core/src/engine/kana_parser.cpp
>    if (accent_index == std::nullopt) throw std::runtime_error("accent not found in accent phrase: " + phrase);
```suggestion
  if (!accent_index) throw std::runtime_error("accent not found in accent phrase: " + phrase);
```

2022-04-21 14:56 UTC, Yosshi999 commented on core/src/engine/kana_parser.cpp
>    if (accent_index == std::nullopt) throw std::runtime_error("accent not found in accent phrase: " + phrase);
あと83行目もありますが、そこに関しては「中身があるならthrow」というぱっと見非自明なif文なのでどちらが可読性が良いのかは不明です

2022-05-15 09:04 UTC, y-chan commented on core/src/engine/kana_parser.cpp
>    if (accent_index == std::nullopt) throw std::runtime_error("accent not found in accent phrase: " + phrase);
83行目のことも考慮して現在のコードになっています。
統一したほうが可読性が高いと思うので、こちらもそのままにすべきと思いましたが、どうでしょうか?

2022-05-15 09:26 UTC, Yosshi999 approved these changes

2022-05-15 09:26 UTC, Yosshi999 commented on core/src/engine/kana_parser.cpp
>    if (accent_index == std::nullopt) throw std::runtime_error("accent not found in accent phrase: " + phrase);
なるほど、意図的なものであればOKです

2022-05-15 14:12 UTC, PickledChair approved these changes
LGTM！

2022-05-15 14:19 UTC, PickledChair commented
@Oyaki122 申し訳ないです、change request があるのを見落としていました。再レビューをお願いしたいです……！

2022-05-28 03:21 UTC, Oyaki122 commented
遅れてしまい大変申し訳ありません
LGTMです！

2022-05-28 03:22 UTC, Oyaki122 approved these changes
遅れてしまい大変申し訳ありません
LGTMです!

2022-05-28 03:22 UTC, merged