kana_parser 実装
VOICEVOX/voicevox_core pull request #155
Opened 2022-06-10 07:37 UTC by nebocco

## 内容

core/src/engine/mora_list.cpp, kana_parser.cpp の内容を Rust で実装しました。

## 関連 Issue

ref #128

## その他

存在する関数を一通り実装し、簡単なテストを書きました。とりあえずこれ自体で機能が完結しているものを作ろうとしたので、以下のような修正点・調整点が残っています。

- エラーが独自型である（core の Error とは別物）
- モジュールの階層構造をどうするか、整理整頓
- 関数の公開範囲をどうするか
- Rust 的にはもう少しすっきり書けそう

また、C++ での実装で計算量の悪い箇所がありましたがそのまま残しています。

2022-06-10 07:39 UTC, qwerty2501 commented
元がengineディレクトリ切ってるのでそれに寄せてengine module作ったほうが良いと思います

2022-06-10 07:41 UTC, qwerty2501 commented
エラーを独自型にした理由ってなんかあったりするんですか？

2022-06-10 07:46 UTC, nebocco commented
> エラーを独自型にした理由ってなんかあったりするんですか？

一旦書き写すにあたって閉じたモジュールにしたかったためです。TTS機能の実装ももう少し先になりそうなのでそのときに対応させればいいかなと思っていました。

2022-06-10 07:51 UTC, PickledChair commented
@nebocco PR ありがとうございます！　細かいところは後で詳しく見てみたいと思います。

プロジェクトの構成については @qwerty2501 さんの意見

> 元がengineディレクトリ切ってるのでそれに寄せてengine module作ったほうが良いと思います

に同意で、例えば

```
voicevox_core
├── Cargo.toml
├── build.rs
└── src
    ├── c_export.rs
    ├── engine
    │   ├── kana_parser.rs
    │   └── mod.rs
    ├── error.rs
    ├── internal.rs
    ├── lib.rs
    ├── result.rs
    └── status.rs
```

みたいな構造にするのが良いのかな、と思いました！

2022-06-10 14:29 UTC, Hiroshiba commented
あ！！
これはただの思いつきですが、engineディレクトリも良いのですが別クレート（例えばvoicevox_ttsとか）にすると、最終的にdll分けたりopenjtalkを含めたり含めなかったりできるかもと感じました。
（でもプルリクの主旨とは異なるので、engineディレクトリでも問題ないと思います。）

2022-06-10 14:29 UTC, Hiroshiba commented
すみません、間違えました🙇‍♂️

2022-06-10 15:12 UTC, PickledChair requested changes
とりあえずテスト以外のコードをレビューしました（すみません、テストコードはまた後ほどレビューします……！）。確認よろしくお願いいたします。

2022-06-10 15:12 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    text.pop(); // remove last delimiter
元のコードにはなかった処理だと思うのですが、どのような意図でしょうか？（すみません、私が理解できていないだけかも知れません）

2022-06-10 15:25 UTC, Hiroshiba commented on crates/voicevox_core/src/engine/kana_parser.rs
> +}
ライセンスに関しては、ライセンスが書かれてるこちらへのリンクを書いて頂ければ！
http://open-jtalk.sourceforge.net/readme_open_jtalk.php

2022-06-10 15:35 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +}
なるほど、ありがとうございます。確かにリンク記載が簡潔で良いですね！（あと、オリジナル開発者についての最低限の記載もあった方が良いでしょうか）

2022-06-10 15:42 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +                if phrase.find(WIDE_INTERROGATION_MARK).unwrap() == phrase.len() - 1 {
あ、こちらの方が簡潔かもしれません……！

```suggestion
                if phrase.last().unwrap() == '？' {
```

2022-06-10 15:58 UTC, Hiroshiba commented on crates/voicevox_core/src/engine/kana_parser.rs
> +}
あ、すみません、MITではなかったので全文記載が必要そうです！ 🙇‍♂️

2022-06-11 09:39 UTC, qwerty2501 commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
エラーのパターンが少なければ `Error` のほうに `KanaParseXxx` といった感じで追加しても良いと思います。
多いと感じるんであれば以下のような感じに定義するですかね
```rust
// error.rs
#[derive(Error,Debug,PartialEq)]
enum Error{
    ...
    #[error(transparent)]
    KanaParse(#[from] engine::kana_parse::KanaParseError),
    ...
}
```

```rust
// engine/kana_parser.rs
#[derive(Error,Debug,PartialEq)]
enum KanaParseError{
    
    #[error("accent cannot be set at beginning of accent phrase: {phrase}")]
    AccentCannotBeSetBegining{
        phrase:String, 
    },
   #[error("second accent cannot be set at an accent phrase: {phrase}")]
    AccentCannotBeSetSecond{
       phrase:String,
    },
    #[error("unknown text in accent phrase: {}")]
    UnknownText{
       phrase:String,
    },
    
}
```

> また、ついでに type KanaParseResult<T> = std::result::Result<T, KanaParseError>; と定義して、以降の関数の戻り値の型として用いても良いように感じました（余計かもしれません。他の方の意見も聞きたいです）。


Errorの方に `#[from]` を使って定義すれば ?シンタックスシュガーを使った際に自動変換できます

2022-06-12 01:04 UTC, nebocco commented
レビューありがとうございます。修正いたします。

2022-06-12 01:14 UTC, nebocco commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
こちらに関してなのですが、現在コア側が持っている `enum Error` のようなものをエンジン側でも作ったうえで、
```rust
enum Error {
    CoreError(#[from] CoreError),
    EngineError(#[from] EngineError),
}
```

```rust
enum EngineError {
    # ...
    KanaParseError(何か),
    # ...
}
```
とすると `Error` が肥大化せずに済むんじゃないかな、と想像していました。
KanaParseError の内容を細分化しなかったのも肥大化を防ぎたいという考えだったのですが、こうしたエラーハンドリングは可能な限り細分化して独自の enum を与えたほうがいいでしょうか？

2022-06-12 01:42 UTC, nebocco commented on crates/voicevox_core/src/engine/kana_parser.rs
> +                if phrase.find(WIDE_INTERROGATION_MARK).unwrap() == phrase.len() - 1 {
こちらの処理ですが、フレーズ中に `'？'` が 2 つ以上含まれていた場合に検出できるようにするため、 `last()` で末尾のみを見るのではなく `find()` で最も左側にある `'？'` がどこにあるかを確認しています。

2022-06-12 01:57 UTC, nebocco commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    text.pop(); // remove last delimiter
元々の実装では、delimiter の追加処理は末尾の phrase 以外に対して行われていました。
https://github.com/VOICEVOX/voicevox_core/blob/c47d05576e04360735c29de3e4fc73424440c48c/core/src/engine/kana_parser.cpp#L180-L185
この if 文を無くしてしまい全 phrase に対して delimiter を追加して、その代わりに最後に追加した delimiter を `pop()` しています。

2022-06-12 01:59 UTC, nebocco commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    text.pop(); // remove last delimiter
今気づいたんですが、そもそもこの for 文が
https://github.com/VOICEVOX/voicevox_core/blob/c47d05576e04360735c29de3e4fc73424440c48c/core/src/engine/kana_parser.cpp#L160
なので、上記の if 文は常に true となっていますね
文末にも delimiter を付加する仕様として実装されているのでしょうか……？

2022-06-12 02:06 UTC, nebocco commented
> あ！！ これはただの思いつきですが、engineディレクトリも良いのですが別クレート（例えばvoicevox_ttsとか）にすると、最終的にdll分けたりopenjtalkを含めたり含めなかったりできるかもと感じました。 （でもプルリクの主旨とは異なるので、engineディレクトリでも問題ないと思います。）

ご提案ありがとうございます。確かに最終的には tts 側の機能は別クレートにまとめてしまったほうがよさそうですね。ただ engine モジュールごとまるっとコピペしてしまえば クレートを切り分けるのは比較的簡単だと思うので、クレート分割は後々 tts 機能を本格的に実装していくタイミングに譲ろうと思います。

2022-06-12 02:28 UTC, nebocco commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
> エラーメッセージが複数ありそうだったので、エラーをまじめに定義しようとすると enum になりそうですが、プロジェクト全体で Error をどのように扱うかに関わると思うので、独自 Error 型の定義はとりあえずは今の形で良いと思いました……！

こちらに同意します。将来的に間違いなく修正することにはなるのですが、ひとまずこのままにさせていただきます。

2022-06-12 02:38 UTC, nebocco commented
ひとまずいただいたレビューのうち以下の二点以外を修正しました。
- https://github.com/VOICEVOX/voicevox_core/pull/155#discussion_r894665763
- https://github.com/VOICEVOX/voicevox_core/pull/155#discussion_r894633802

2022-06-12 02:44 UTC, qwerty2501 commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
その辺は好みですが、Error型を細分化しすぎるのもデメリットはあります。
voicevox_coreは現状Error型のパターンで結果コードが1:1で対応していますが、細分化した場合はこれに対して適切な対応を作る必要がある(考慮事項が増える)というのはあります。
またエラーハンドリング処理が煩雑になるかなとは個人的には思います。matchがネストするので
最後に扱う型が増えるので単純にメンテナーの負担が増えるというのもありますね。

細分化するのであれば細分化するルールは設けるべきでしょう。module単位で持つようにするなど

2022-06-12 02:47 UTC, nebocco commented on crates/voicevox_core/src/engine/kana_parser.rs
> +fn text2mora_with_unvioce() -> std::collections::BTreeMap<String, MoraModel> {
特に理由はなかったので `HashMap` に変更します。

2022-06-12 02:59 UTC, nebocco commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
確かにそうですね。
kana_parser 自体コンパクトな機能ですし、表示されるメッセージ（保持している `String`）とエラー位置が一対一対応しているので KanaParser をさらに細かく分ける必要はないんじゃないかなと感じています。

2022-06-12 03:32 UTC, qwerty2501 commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
まあ今後エラーが複雑化して細かく分けたいとなる可能性を考えると今から細分化するルールを設けるのはありかもしれません。あとからやるのは手間がかかりそうなので
最終的にはOwner様の気持ち次第ですかね。

2022-06-12 09:07 UTC, Hiroshiba commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
VOICEVOXライブラリはまだまだベータ版で実装速度とメンテナンスの容易性を優先したいのと、どの粒度のエラーハンドリングの需要があるのかまだ掴めてないのとで、いったん細分化は後回しがいいかなと思います。

ちなみになのですが、ParseError(string)にしても、そのstring（エラーメッセージ？）をC APIでいい感じに返せないかもしれません。
エラーメッセージがないのはデバッグに不便なので、いったんstderr辺りに吐くようにしちゃうのが今の落とし所かもです。

2022-06-12 09:09 UTC, Hiroshiba commented
TTS用のクレート分割は後のタイミングで大丈夫だと思います！

2022-06-12 09:29 UTC, qwerty2501 commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
> ちなみになのですが、ParseError(string)にしても、そのstring（エラーメッセージ？）をC APIでいい感じに返せないかもしれません。
エラーメッセージがないのはデバッグに不便なので、いったんstderr辺りに吐くようにしちゃうのが今の落とし所かもです。

すでにErrorからResultCode変換の際にその処理は入ってます

2022-06-12 09:53 UTC, Hiroshiba commented on crates/voicevox_core/src/engine/kana_parser.rs
> +struct ParseError(String);
おお！！なるほどです！！

2022-06-26 04:42 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +                if phrase.find(WIDE_INTERROGATION_MARK).unwrap() == phrase.len() - 1 {
> フレーズ中に `'？'` が 2 つ以上含まれていた場合に検出できるようにする

なるほど、確かにそうですね！　指摘ありがとうございます、考慮できていませんでした🙏

2022-06-26 05:12 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    text.pop(); // remove last delimiter
なるほど、説明ありがとうございます！　私が問題を理解できていませんでした……！

> これが正しい（ `if (i < accent_phrases.size() - 1) { ` の間違いではない）のであれば最後の `text.pop()` は削除するべきですね

おそらく元の実装が間違いで、`if (i < accent_phrases.size() - 1) { ` が本来の意図である感じがしますね……。 https://a-quest.com/archive/manual/siyo_onseikigou.pdf の「2.3 区切記号」「2.4 区切記号の違い」を読む限りは、文末に区切り文字がくることは想定されていないような気がします（つまり最後の `text.pop()` は必要そうです）。元の実装者である @y-chan さんにもお話を聞きたい感じがしました……！

2022-06-26 05:41 UTC, PickledChair requested changes
申し訳ありません、なかなかレビューの時間が取れず、かなりお待たせしてしまいました……！　テストコードについてもレビューしました。確認よろしくお願いします。

他の Rust 実装関連の PR がいくつかマージされ、おそらくコンフリクトが発生しているので、Draft を外す際は解消をよろしくお願いいたします……！

2022-06-26 05:41 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +        ];
voicevox_core クレートのテストは基本的に `rstest` と `pretty_assertions` の `assert_eq!` を使って実装している感じなので、`kana_parser` のテストも同様にすると良いのかな、と感じました！

参考：以下のようにテストケースごとの入力と期待される出力の組を関数外に書くことができます
https://github.com/VOICEVOX/voicevox_core/blob/2dabb4cfb40a99b15b305f249b1774c34befdbec/crates/voicevox_core/src/status.rs#L262-L284

2022-06-26 05:41 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +            assert!(text_to_accent_phrase(text).is_ok());
`assert!` を使ったアサーションは、期待と異なる出力だった時にその出力を表示させるのが良いと思います……！（他の同様の箇所についてもよろしくお願いします）

```suggestion
            let result = text_to_accent_phrase(text);
            assert!(result.is_ok(), "{:?}", result);
```

2022-06-26 05:41 UTC, PickledChair commented on crates/voicevox_core/src/engine/mora_list.rs
> +    }
こちらも `rstest` の使用をお願いしたいです……！

2022-06-26 09:37 UTC, y-chan commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    text.pop(); // remove last delimiter
コード読んでみました。
ご指摘の通りC++実装の間違い(Python実装を書き写すときに誤って見落とした)のだと考えられます...!

個人的には、元の実装に合わせて`if (i < accent_phrases.size() - 1) {`を使うほうがいいようにも感じましたが、現在の実装の方がキレイな気もするので、このままでよいような気もします...!

2022-06-26 09:45 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    text.pop(); // remove last delimiter
@y-chan 

了解です！　意見ありがとうございます……！

@nebocco 

今のままで良さそうです……！（あるいはif分岐を使うように書き換える）

2022-06-29 02:58 UTC, nebocco commented
レビューありがとうございました。ご指摘いただいた点を修正いたしました。

2022-06-29 03:55 UTC, Hiroshiba approved these changes
LGTM！！！

まだ実際に音声合成として動かせてないかもですが、一旦マージしちゃうのが良いのかなと思っています･･･！！

2022-06-29 10:58 UTC, PickledChair requested changes
すみません、前回のレビューが中途半端な書き方になってしまい、少し意図が伝わらなかった部分があったようなので、追加の change request を出しました（rstest を使うように書いたことについてなのですが、機能的に便利だから使うということの他に、voicevox_core クレートのテストが基本的に全て rstest を使って書かれており、可読性を上げるために全てのテストで rstest を似たような形式で用いたい、という意図があってコメントしていました。わかりづらくて申し訳ありませんでした……！）。

2022-06-29 10:58 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    }
このテスト関数も rstest で書くと、他のテストと形式が同じになるので後で読みやすくなると思います。

`KanaParseError` に `PartialEq` を実装して `result` と直接比較できるようにすると `expected` として `KanaParseResult` を渡せるのでわかりやすく書けそうですが、エラーメッセージを比較したい訳でもないので、書くとしたら以下のように `expected` として `bool` 値を渡す書き方が良いかも、と思いました（前に `assert!` の書き方についてコメントした手前、`assert_eq!` を書くという違う主張になってしまいすみません……！）。

```suggestion
    #[rstest]
    #[case("ア_シタ'ワ", true)]
    #[case("ユウヒガ'", true)]
    #[case("_キ'レイ", true)]
    #[case("アクセントナシ", false)]
    #[case("アクセ'ント'タクサン'", false)]
    #[case("'アクセントハジマリ", false)]
    #[case("不明な'文字", false)]
    fn test_text_to_accent_phrase(#[case] text: &str, #[case] result_is_ok_expected: bool) {
        let result = text_to_accent_phrase(text);
        assert_eq!(result.is_ok(), result_is_ok_expected, "{:?}", result);
    }
```

2022-06-29 10:58 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    }
これも以下のように rstest を使うとよさそうです。

```suggestion
    #[rstest]
    #[case("テ'ス_ト/テ_ス'ト、_テ'_スト？/テ'ス_ト？", true)]
    #[case("クウハクノ'//フレーズ'", false)]
    #[case("フレー？ズノ'/トチュウニ'、ギモ'ンフ", false)]
    fn test_parse_kana(#[case] text: &str, #[case] result_is_ok_expected: bool) {
        let result = parse_kana(text);
        assert_eq!(result.is_ok(), result_is_ok_expected, "{:?}", result);
    }
```

2022-06-29 10:58 UTC, PickledChair commented on crates/voicevox_core/src/engine/kana_parser.rs
> +    #[test]
このテストは入力と出力の組みが１組しかないので `#[case]` は書かなくてよいと思いますが、一応 rstest にするのが良いと思います。

```suggestion
    #[rstest]
```

2022-06-29 18:18 UTC, qwerty2501 commented on crates/voicevox_core/src/engine/model.rs
> +}
いったんderive_newとderive_getters使ってみようという方針になっていたはずなので各structにdrive(new,Getter)をしてfieldのpubを外してstructのimmutable性を高めたほうが良いと思います
```suggestion
#[derive(Clone, Debug, new, Getter)]
pub(super) struct MoraModel {
    text: String,
    consonant: Option<String>,
    consonant_length: Option<f32>,
    vowel: String,
    vowel_length: f32,
    pitch: f32,
}

#[allow(dead_code)] // TODO: remove this feature
#[derive(Debug, new, Getter)]
pub(super) struct AccentPhraseModel {
    moras: Vec<MoraModel>,
    accent: usize,
    pause_mora: Option<MoraModel>,
    is_interrogative: bool,
}

#[allow(dead_code)] // TODO: remove this feature
#[derive(new, Getter)]
pub(super) struct AudioQueryModel {
    accent_phrases: Vec<AccentPhraseModel>,
    speed_scale: f32,
    pitch_scale: f32,
    intonation_scale: f32,
    volume_scale: f32,
    pre_phoneme_length: f32,
    post_phoneme_length: f32,
    output_sampling_rate: u32,
    output_stereo: bool,
    kana: String,
}
```

2022-06-30 08:50 UTC, nebocco commented on crates/voicevox_core/src/engine/model.rs
> +}
とりあえず new と Getters を追加したのですが、ごく一部の属性は mutable に扱うことがあるため、最低限の広さで public としてみました。

https://github.com/VOICEVOX/voicevox_core/blob/42e6cfdf7ca6d8370061f56853c1d41c7a31a9db/crates/voicevox_core/src/engine/kana_parser.rs#L151-L162
https://github.com/VOICEVOX/voicevox_core/blob/42e6cfdf7ca6d8370061f56853c1d41c7a31a9db/crates/voicevox_core/src/engine/model.rs#L17-L24

2022-06-30 09:13 UTC, qwerty2501 commented on crates/voicevox_core/src/engine/model.rs
> +}
accessibilityを変えるのではなく、必要な部分にだけsetterをAccentPhraseModel に生やすように出来ますか？
機能上全てのフィールドを初期化後に変更する可能性があるのであればGettersを使わずに初めからpublicにしたほうがよいですが、今回のように部分的に変更するのであればsetterが良いと思います

2022-07-01 04:28 UTC, PickledChair approved these changes
LGTM！　PR ありがとうございました。長いレビュー期間になってしまい大変お待たせしてしまいました。お疲れ様でした！

https://github.com/VOICEVOX/voicevox_core/pull/155#discussion_r910263065 への対応に関して、 @qwerty2501 さんが特に問題ないという感じでしたらマージで良いと思います！

2022-07-01 04:30 UTC, qwerty2501 approved these changes
対応はいってたんですね LGTM

2022-07-01 04:32 UTC, merged

2022-07-01 04:34 UTC, Hiroshiba commented
PRありがとうございました！！
コアは結構ほしい機能がまだまだあったりするので、よかったらまたPRいただけると心強いです！！！