audio_query 関数の返すクエリの初期値に create_kana の結果を格納
VOICEVOX/voicevox_core pull request #254
Opened 2022-08-27 17:01 UTC by PickledChair

## 内容

エンジンの `audio_query` の結果と比較して気づきましたが、コアの `VoicevoxCore::audio_query` 関数から返ってくる `AudioQuery` の `kana` フィールドが空文字列になっていました。エンジンでは `create_kana` で作られた AquesTalk 記法の文字列です。エンジンの以下の部分が対応するコードです。

https://github.com/VOICEVOX/voicevox_engine/blob/8057ee439767c9bfe14f323bb20f8391006d6bfd/run.py#L123-L146

エンジンと同じ挙動になるように変更を加えました。

## 関連 PR

ref #244

2022-08-27 17:40 UTC, qryxip approved these changes
仮置きしたのがそのままでした...

LGTM

2022-08-28 00:47 UTC, qwerty2501 requested changes
お手数ですが、この部分についての簡単なテストコードの追加もお願いできますか？

2022-08-28 01:09 UTC, qwerty2501 commented
ここも allow(dead_code) 外す必要がありそう
https://github.com/VOICEVOX/voicevox_core/blob/main/crates/voicevox_core/src/engine/model.rs#L53-L54

2022-08-28 13:44 UTC, PickledChair commented
指摘された `allow(dead_code)` の削除と、簡単なテストの実装を行いました！

2022-08-28 13:49 UTC, qwerty2501 approved these changes
LGTM

2022-08-28 13:49 UTC, merged