C API内でのエラー処理をRustらしくする
VOICEVOX/voicevox_core pull request #295
Opened 2022-10-01 10:03 UTC by qryxip

## 内容

C API内でのエラー処理を`Result`中心のものにします。

## 関連 Issue

Resolves #292.

## その他

2022-10-01 11:14 UTC, qryxip commented on crates/voicevox_core_c_api/src/helpers.rs
> +pub(crate) fn fallible_c_api(result: CApiResult<()>) -> VoicevoxResultCode {
これの名前に悩んでいます。
`convert_result`の続投も考えたのですが、この関数は

1. `CApiError`をstderrに出力
2. `Result<(), CApiError>`を`VoicevoxResultCode`に変換

という2つの役割を現在持っているため"convert"は少々無理が出てくると思いました。
他の候補としては次を考えています。

- `process_result`
- `into_result_code_with_error`  ([Cargoにならい](https://docs.rs/cargo/0.65.0/cargo/?search=_with_error))

2022-10-01 12:06 UTC, qryxip commented
- 関数`result_code`を関数内関数にして外部から触れなくしました。

2022-10-01 12:51 UTC, qwerty2501 approved these changes
LGTM

2022-10-01 12:55 UTC, qwerty2501 commented on crates/voicevox_core_c_api/src/helpers.rs
> +pub(crate) fn fallible_c_api(result: CApiResult<()>) -> VoicevoxResultCode {
`convert_result` への違和感は感じていたのですが、かといってエラー表示するのを関数名に含めてしまうと長過ぎるので入れてませんでした。
エラー表示はしてますが主目的としては変換なので `convert_result` でも良いかなとは思ってます

2022-10-01 13:44 UTC, PickledChair commented on crates/voicevox_core_c_api/src/helpers.rs
> +pub(crate) fn fallible_c_api(result: CApiResult<()>) -> VoicevoxResultCode {
関数の定義を見なくても、関数名とシグネチャだけで何をしているのか分かりやすい方が良いと思ったので、案として挙げられている `into_result_code_with_error` は良い候補の１つと感じました（「Cargoにならい」の文脈を理解している前提で、ですが……）。また「関数名とシグネチャだけで何をしているのか分かりやすい」という点では確かに `convert_result` も候補に上がると感じました（エラー表示する点を説明しなくて良いとするならば）。

前者と後者で他に何が違うか考えた時、関数名の焦点が「何を戻り値として返すか」（`into_result_code_with_error`）なのか、「何を引数として取るか」（`convert_result`）なのか、の違いがあると思いました。

個人的には、今回のコードを読んでいるときに「結果として何が得られるか」という情報の方が早く欲しいと感じたので、`into_result_code_with_error` の方が多少ありがたいと感じました（`convert_result` だと、得られる結果を知るのに IDE の支援が欲しくなるので、手順がワンステップ増えてしまい少し追加の労力があるな、と感じました）。また、「エラー表示する点を説明しなくて良い」とするならば `_with_error` を省くことを考えても良いかもしれません。

この辺りは個々人の感覚によると思うので正解はなさそうですが……。自分の意見としては「関数名とシグネチャだけで何をしているのか分かりやすい」物が良く、さらに言えば「関数名だけで何をしているのか分かりやすい」物がさらに良く感じ、その点で前者の方が読みやすく感じた、ということです。

2022-10-02 07:02 UTC, qryxip commented on crates/voicevox_core_c_api/src/helpers.rs
> +pub(crate) fn fallible_c_api(result: CApiResult<()>) -> VoicevoxResultCode {
`into_result_code_with_error`にしようと思います。
軽く調べたところ`_with_error`という命名はそこそこ一般的なように見えました。

- https://grep.app/search?q=exit_with_error ([例その2](https://github.com/torvalds/linux/blob/f86d1fbbe7858884d6754534a0afbb74fc30bc26/tools/testing/selftests/bpf/xskxceiver.c#L124))
- https://grep.app/search?q=close_with_error ([例](https://docs.rs/ntex-amqp/latest/ntex_amqp/struct.Connection.html#method.close_with_error))
- https://grep.app/search?q=return_with_error
- https://grep.app/search?q=break_with_error
- https://grep.app/search?q=convert_with_error
- https://grep.app/search?q=into_%5Ba-z0-9_%5D%2Awith_error&regexp=true&filter[lang][0]=Rust&filter[lang][1]=Python

2022-10-02 07:12 UTC, qryxip commented
- `fallible_c_api`を`into_result_code_with_error`にリネーム
- `into_result_code_with_error`をリファクタし、エラー表示と変換の2つの処理をしていることをわかりやすく

2022-10-02 07:15 UTC, PickledChair commented on crates/voicevox_core_c_api/src/helpers.rs
> +pub(crate) fn fallible_c_api(result: CApiResult<()>) -> VoicevoxResultCode {
@qryxip 了解です。恐らく全員が一致できる名前を考えるのは難しいと思ったので、妥当と思われる名前を好きに選んで良いと思いました！

2022-10-02 07:53 UTC, PickledChair requested changes
１箇所コメントしました

2022-10-02 07:53 UTC, PickledChair commented on crates/voicevox_core_c_api/src/lib.rs
> +    fn fallible_c_api_works(#[case] result: Result<()>, #[case] expected: VoicevoxResultCode) {
テスト名の修正もよろしくお願いします！

```suggestion
    fn into_result_code_with_error_works(#[case] result: Result<()>, #[case] expected: VoicevoxResultCode) {
```

2022-10-02 07:54 UTC, qryxip commented on crates/voicevox_core_c_api/src/lib.rs
> +    fn fallible_c_api_works(#[case] result: Result<()>, #[case] expected: VoicevoxResultCode) {
忘れてました。

2022-10-02 07:59 UTC, PickledChair commented on crates/voicevox_core_c_api/src/lib.rs
> +    fn fallible_c_api_works(#[case] result: Result<()>, #[case] expected: VoicevoxResultCode) {
あ、一行が長すぎてlintチェック通らなかったですね……

2022-10-02 08:20 UTC, PickledChair approved these changes
LGTM！　異論がなければマージして良いと思いました。

2022-10-02 09:47 UTC, merged