Python APIのドキュメントを書く
VOICEVOX/voicevox_core pull request #316
Opened 2022-10-21 15:13 UTC by qryxip

## 内容

エディタ上で表示するため、PythonAPIのdocstringだけ書いてしまいます。

![image](https://user-images.githubusercontent.com/14125495/197229389-b97ce937-0f7e-4c57-bddf-5507e6441bca.png)

## 関連 Issue

#294

## その他

2022-10-21 16:11 UTC, Hiroshiba approved these changes
LGTM！！

このドキュメントも半自動的に生成できるとかっこいいかも、とちょっとだけ思いました！
まあでもたぶんRust側の関数と１：１対応しなさそうだし、簡単にできる方法はなさそうですかね･･･。

2022-10-22 12:03 UTC, qryxip commented
半自動的に生成する方法として次のような方法を思い付きました。

1. ドキュメントの素となる構造体をTOMLかYAMLで書く (変なことをしようとしなければ、いわゆる「[YAMLでプログラミング](https://twitter.com/search?q=%22yaml%E3%81%A7%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%22%20min_faves%3A1&src=typed_query&f=live)」は避けられるはず)
2. 1.をC/Python API用のドキュメントに変換するツールを/crates/gen-docsとして作る
3. `#[cfg(doc)]`のときだけC APIのbuild.rs内で2.を呼び、rustdocを
    ```rust
    #[doc = include_str!(concat!(env!(OUT_DIR), "/docs/voicevox_predict_intonation.txt"))]
    ```
    のような形にすることで2.の生成物がDoxygenのドキュメントになるようにする
5. 今ある_rust.pyiのdocstring部分だけ差し替え可能にできるようなテンプレートをLiquidとかAskamaで作る
6. Python APIのbuild.rsでも2.を呼び、コンパイルのタイミングで4.を生成する (これの時間がかかるようならC APIのように/crates/xtaskに退避させて手動で起動するようにする)

作るのはおそらくそこまで難しくはなく、メンテするのも多分できると思います。ただそのリターンが「同じ文章をN回書かずに済む」だけということを考えると…

2022-10-22 13:28 UTC, PickledChair requested changes
少し気になったところがあったのでコメントしました。

ドキュメントの自動生成については @qryxip さんとだいたい同意見で、技術的には可能とは思いますが、労力に見合った便利さが得られるかちょっと微妙に感じています。メンテナンスを続けた上で、必要性を十分感じるようであれば自動生成の仕組みを実装する、くらいでも良いのかもしれません。

2022-10-22 13:28 UTC, PickledChair commented on crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
> +            終了アクセントフレーズデータ。
細かいかもしれませんが、これらの引数の説明内容にやや違和感を覚えました。
「開始アクセント」や「開始アクセントフレーズ」というような表現は、用語の使い方として正しくない気がしています（「開始アクセント」「開始アクセントフレーズ」という言葉の指すものはおそらく存在しないと思われます。ただし、私もこれらの用語の適切な用法を把握していないため、 @Hiroshiba さんにどのような説明が適切かをお聞きしたいと思います）。

エンジンの方の引数の説明が https://github.com/VOICEVOX/voicevox_engine/blob/9f5a14d6f098a5068ab60e111480b0a042214390/voicevox_engine/synthesis_engine/synthesis_engine.py#L142-L151 にあったので、こちらを参考にした変更案を以下に示しました。意図としてはおそらく上から順に「どのモーラがアクセントの開始位置か」「どのモーラがアクセントの終了位置か」「どのモーラがアクセント句の開始位置か」「どのモーラがアクセント句の終了位置か」を示すデータであると理解しています（間違っていたらすみません）。

```suggestion
        start_accent_list
            アクセントの開始位置のデータ。
        end_accent_list
            アクセントの終了位置のデータ。
        start_accent_phrase_list
            アクセント句の開始位置のデータ。
        end_accent_phrase_list
            アクセント句の終了位置のデータ。
```

2022-10-22 13:35 UTC, qryxip commented on crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
> +            終了アクセントフレーズデータ。
説明文はC APIから持って来ているので、こちらも修正ですかね。

https://github.com/VOICEVOX/voicevox_core/blob/b9dd6bb12fb7c832e5fd7350efe75e880740cac3/crates/voicevox_core_c_api/src/lib.rs#L182-L185

2022-10-22 14:19 UTC, Hiroshiba commented on crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
> +            終了アクセントフレーズデータ。
たしかにちょっとニュアンスが違いそうですね！
お手数ですが、ついでにc_api側も変えていただければ 🙇

2022-10-22 14:22 UTC, qryxip commented
C API側も更新しました。

2022-10-22 14:23 UTC, Hiroshiba commented
自動生成に関して、サクッと作れる方法がないのであれば実装しないという方針が良いのかなと思いました！

Rust側のドキュメントが変わったときにpython側のドキュメントを変え忘れる、ということが往々にしてありそうですが、まあドキュメントが乖離してしまってもそこまで問題ではない気がするので気にしなくても良さそうですね･･･！

2022-10-22 15:19 UTC, PickledChair approved these changes
LGTM！

> Rust側のドキュメントが変わったときにpython側のドキュメントを変え忘れる、ということが往々にしてありそうですが、まあドキュメントが乖離してしまってもそこまで問題ではない気がするので気にしなくても良さそうですね･･･！

その問題はありそうですね……。この問題の改善へのモチベーションが高くなった時点で Issue が作られるのを待つか、今 Issue を作るか迷うところです。

2022-10-22 15:19 UTC, merged