Fix parameter names in python names
VOICEVOX/voicevox_core pull request #320
Opened 2022-10-22 12:31 UTC by qryxip

## 内容

`sed -i 's/_list/_vector/g' ./crates/voicevox_core_python_api/**/{*.pyi,*.rs}`しました。

## 関連 Issue

Fixes #317.

## その他

#316 に続くPRです。

2022-10-22 20:59 UTC, Hiroshiba approved these changes
LGTM！！

2022-10-23 00:06 UTC, PickledChair requested changes
一箇所確認よろしくお願いします！

2022-10-23 00:06 UTC, PickledChair commented on crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
> +            終了アクセントフレーズデータ。
この箇所の引数の説明が元に戻ってしまっていました

2022-10-23 06:00 UTC, qryxip commented on crates/voicevox_core_python_api/python/voicevox_core/_rust.pyi
> +            終了アクセントフレーズデータ。
コンフリクトを適当に解消してしまってました。

#316 からcherry-pickしてきました。

2022-10-23 06:10 UTC, PickledChair approved these changes
LGTM！

テストが通ったらマージします。

2022-10-23 06:18 UTC, merged