Onnx版を頭へ持ってくる
VOICEVOX/voicevox_core pull request #42
Opened 2021-11-28 11:06 UTC by Yosshi999

## 内容

- [ ] docker版の修正
README：
- [ ] ONNXRuntimeのダウンロード手順を表記
- [ ] ONNX版暗号化済みコアの導入手順の表記
pip install時：
- [ ] ONNXRuntimeを自動ダウンロード
- [ ] CUDAオプション
- [ ] 依存モジュールのcmake buildの省略（Releaseからコアをダウンロードするときはそれに紐づける必要がある）

## 関連 Issue
close #27 

## その他

2021-11-29 18:27 UTC, Hiroshiba commented
draftですが、最初の手順に関してすでにコメントができそうだったので、コメントしてみます！
（手順書いて頂くの、認識を合わせられるのでとても良いと感じました、ありがとうございます！！）

`ONNX版暗号化済みコアの導入手順の表記`
こちらに関しては、暗号化周りのロジックも考える必要があって、難度が高そうです。
プルリクエストのタイトルと少し乖離しそうな気がしました。
なのでこちらは別にしても良いのかなと思いました。

あと結構大きなプルリクエストになるかもです。
その場合はこのタスク１つ１つの粒度くらいでプルリクエストを作って頂くと、レビューもマージも結果的に早くなると思います。

お待ちしております・・・！

2021-11-30 08:43 UTC, Yosshi999 commented
プルリクを一つにまとめようとした意図としては、これらを揃えずにマージすると一時的にmain branchが不完全な状態になってしまうためです。リソースが最低限そろっているversion 0.0.1に戻すという手もありますが、ほかのvoicevox_*と乖離してしまいます。

main以外のブランチを作ってそちらに段階的にレビュー・マージをするのはどうでしょうか

2021-12-01 11:18 UTC, Hiroshiba commented
> 揃えずにマージすると一時的にmain branchが不完全な状態になってしまうため

なるほどです！
であれば、今も他のvoicevox_*と協調できていない状態なので、段階的にマージしても大丈夫かなと思います。
（実際、バージョン0.9.0はかなり昔のcommitから派生してタグを付けて運用しています。）

どんどんプルリクエスト送って頂ければ・・・！

2021-12-02 19:06 UTC, Yosshi999 commented
とりあえずこの状態でレビューをお願いします

2021-12-03 15:13 UTC, Hiroshiba commented
変更行数もそこまで多くなかったのと、コアはそもそもプルリクエストの数がそこまで多くないことから、頂いたままレビューするのもそこまで難しくなさおうだと感じました。
レビューを始めたいと思います。

@Oyaki122 さんも、もしよかったらコメント等頂ければ！

2021-12-03 15:41 UTC, Hiroshiba requested changes
READMEの整備も助かります、勘違いが起きにくい良い案内だと思いました。

知識がなく、cmake周りのレビューが全くできませんでした･･･
ご存じの方いらっしゃったらコメント頂けると！

2021-12-03 15:41 UTC, Hiroshiba commented on CMakeLists.txt
> +set(ONNXRUNTIME_DIR "${CMAKE_CURRENT_SOURCE_DIR}/onnxruntime-win-x64-1.9.0" CACHE PATH "Path to ONNX Runtime")
自動ビルドのことを考えると、バージョン名やOS環境名は省いて`onnxruntime`ディレクトリにするとあとあと楽かもと感じました。

2021-12-03 15:41 UTC, Hiroshiba commented on README.md
> +環境に対応したONNX Runtimeをダウンロードし、リポジトリに展開します。
`onnxruntime`ディレクトリとして展開します、みたいなこと書いてあげると優しいかもです。

2021-12-03 15:41 UTC, Hiroshiba commented on README.md
> +# --model モデルファイルが置いてあるディレクトリへのパス
たぶん「モデル」という言葉は一般に馴染みがないので、使わないように意識しています。
引数は`--onnx_dir`とし、案内はonnxファイル、とかはどうでしょう。
（onnxruntimeのディレクトリと勘違いされそうなので、この引数名は最良では無いかもです）

2021-12-03 15:41 UTC, Hiroshiba commented on README.md
> +サンプルコードおよび [core.h](./core/csrc/core.h) は [MIT LICENSE](./LICENSE) です。
ちょっとだけ気になったのですが、`csrc`としている理由はなんでしょう👀
個人的には馴染みの深いsrcにしておくほうが将来のミスを防げるのかなとちょっとだけ思いました

2021-12-03 15:41 UTC, Hiroshiba commented on core/__init__.py
> +if sys.platform == 'win32':
こちらの意図はなんでしょう。
win32環境だとこのコードがないと動かないとか･･･？

2021-12-03 15:41 UTC, Hiroshiba commented on core/csrc/core.cpp
> +bool OpenModels(
一般的に大文字始まりはクラスだと思う人が多そうに感じました。
命名規則は統一されていませんが、なんとなくpythonに合わせて、クラス名はCamelCase、変数や関数やメソッドはsnake_caseでどうでしょう。

2021-12-03 15:41 UTC, Hiroshiba commented on core/csrc/core.cpp
> +  return true;
こちらで一旦バイナリロードされている意図としては、将来の暗号化を見据えてということでしょうか？

2021-12-03 15:41 UTC, Hiroshiba commented on core/csrc/core.cpp
> +    const charsetT* decode_path,
`fs::path`で渡したほうが意図がわかりやすいかも・・・？

2021-12-03 15:41 UTC, Hiroshiba commented on setup.py
> +version = '0.0.1'
将来的にVOICEVOX_ENGINE同様にファイルに書き出したいなと思いました。

2021-12-03 15:41 UTC, Hiroshiba commented on setup.py
> +        check_call(['cmake', '--install', '.'], cwd=build_dir)
pip installのときにcmakeコマンドを叩かずに良い感じにビルドする方法も確かあるのですが、すごく大変そうなので、check_callで良いと感じました。

pyopenjtalkとかは結構頑張ってビルドされています。
https://github.com/r9y9/pyopenjtalk/blob/7ad3adc358a4348434844db55b8f181c713c99c7/setup.py

2021-12-03 15:41 UTC, Hiroshiba commented on setup.py
> +        runtime_library_dirs = ["$ORIGIN/lib"]
こちら前も伺ったかもしれないのですが、`$ORIGIN`とはなんでしょう・・・？（コメントで残しておくと優しいかもと感じました）

2021-12-03 15:51 UTC, Yosshi999 commented on README.md
> +サンプルコードおよび [core.h](./core/csrc/core.h) は [MIT LICENSE](./LICENSE) です。
torch (https://github.com/pytorch/pytorch/tree/master/torch/csrc) を真似ましたがsrcでも構いません

2021-12-03 15:53 UTC, Yosshi999 commented on core/__init__.py
> +if sys.platform == 'win32':
win32ではdllロード時、システムのもの以外はpython libraryがあるディレクトリとカレントディレクトリしか見てくれません
https://github.com/pytorch/pytorch/blob/master/torch/__init__.py#L55 からコードを持ってきています

2021-12-03 15:55 UTC, Yosshi999 commented on core/csrc/core.cpp
> +bool OpenModels(
たしかにcore.hに命名規則を合わせたほうがいいですね

2021-12-03 15:55 UTC, Yosshi999 commented on core/csrc/core.cpp
> +  return true;
はい

2021-12-03 15:56 UTC, Yosshi999 commented on setup.py
> +        runtime_library_dirs = ["$ORIGIN/lib"]
コメントに書いておきます

2021-12-03 16:01 UTC, Yosshi999 commented on README.md
> +# --model モデルファイルが置いてあるディレクトリへのパス
この引数はそのままinitializeに渡されるので、core.hにある

> root_dir_path 必要なファイルがあるディレクトリ。

でどうでしょうか

2021-12-03 16:25 UTC, Oyaki122 reviewed
知識が少なくて申し訳ありませんが、ご回答よろしくおねがいします

2021-12-03 16:25 UTC, Oyaki122 commented on .gitignore
> -onnx/lib/
buildフォルダなどがルートに、libがcore内に生成されるようになったわけですが、これらがgitignore登録されていないのにはなにか意図があるのでしょうか？

2021-12-03 16:29 UTC, Yosshi999 commented on .gitignore
> -onnx/lib/
追記忘れていました。

2021-12-03 16:59 UTC, Hiroshiba commented on README.md
> +# --model モデルファイルが置いてあるディレクトリへのパス
なるほどです！
rootだとまあソースコードのrootと間違えられる可能性もありそうですが、ぶっちゃけ他に適した言い方がわからないので、良いと思いました・・・！

2021-12-03 17:00 UTC, Hiroshiba commented on core/csrc/core.cpp
> +  return true;
なるほどです、でしたら暗号化を意図していることをコメントで書いておくと良いかもと思いました！

2021-12-03 17:02 UTC, Hiroshiba commented on README.md
> +サンプルコードおよび [core.h](./core/csrc/core.h) は [MIT LICENSE](./LICENSE) です。
なるほどです。
pytorchの該当ディレクトリはどうやらほかはpythonな一方、このディレクトリだけc++っぽいです。
このモジュールは多分全部c++なので、何かの意図を感じさせないためにsrcで良いかなと感じました！

2021-12-03 17:03 UTC, Hiroshiba commented on core/__init__.py
> +if sys.platform == 'win32':
なるほどです！
そちらのリンクをコメントで書いておくとメンテナンスしやすそうに感じました。
commit idもURLに含めると
https://github.com/pytorch/pytorch/blob/b76117240691f071367517301241620c363a6619/torch/__init__.py#L55
でしょうか

2021-12-03 17:06 UTC, Yosshi999 commented on core/__init__.py
> +if sys.platform == 'win32':
そのように記載しました

2021-12-03 19:05 UTC, Hiroshiba approved these changes
LGTM！！
良いと思います！

ちなみにこちらはGithub Actionsのビルドもできそうでしょうか。
難しそうであれば別issueを建てて頂ければ！

2021-12-04 09:00 UTC, Yosshi999 commented
github action更新しました

2021-12-04 12:46 UTC, Oyaki122 approved these changes
LGTMです
私の分かる範囲では特に問題ありません

2021-12-04 13:12 UTC, merged