yukarin_s_forwardで負の値を取らないようにする　#32
VOICEVOX/voicevox_core pull request #47
Opened 2021-12-07 15:14 UTC by Oyaki122

## 内容

#32 の実装です  

## 関連 Issue

close #32 

## その他
こういう意図であっているんでしょうか…？

2021-12-07 16:15 UTC, Hiroshiba approved these changes
LGTM！！

2021-12-07 16:40 UTC, Yosshi999 requested changes
ちょっと気になった点をコメントしました。

2021-12-07 16:40 UTC, Yosshi999 commented on core/src/core.cpp
> +      if (output[i] < 0) output[i] = PHONEME_LENGTH_MINIVAL;
[MAY] めったに起こらないことですが、0から微小値の間だった場合はそのままになるのは意図通りですか？以下の方が直観的な気がします

```suggestion
      if (output[i] < PHONEME_LENGTH_MINIVAL) output[i] = PHONEME_LENGTH_MINIVAL;
```

2021-12-08 04:43 UTC, Oyaki122 commented on core/src/core.cpp
> +      if (output[i] < 0) output[i] = PHONEME_LENGTH_MINIVAL;
issueに書かれた要件に従ったためこのようにしましたが、そちらのほうが自然だと思いますので修正します

2021-12-08 08:19 UTC, Yosshi999 approved these changes
LGTM!

2021-12-08 08:47 UTC, merged