Add: x86_64-linux-androidを追加
VOICEVOX/voicevox_core pull request #473
Opened 2023-04-24 13:58 UTC by sevenc-nanashi

## 内容

タイトル通り。

## 関連 Issue

- ref: voicevox/voicevox_project#10

## その他

2023-04-24 14:13 UTC, qryxip requested changes
aarch64と同様に`build and deploy workflow`に加えないとビルドできないと思います。

2023-04-24 14:51 UTC, qryxip approved these changes
LGTM!

2023-04-25 18:34 UTC, Hiroshiba commented on .github/workflows/build_and_deploy.yml
> +          echo "AR_$UNDERSCORED_TRIPLE=llvm-ar" >> "$GITHUB_ENV"
actionlintがエラーを吐いてますねぇ。
`$(sed 's/-/_/g' <<< "${{ matrix.target }}")`という記法が怒られてそうです。
（たしかに見慣れない記法だなとは思いました）

actionlintでshellcheckを省けそうでした。
https://github.com/rhysd/actionlint/blob/94c4f0119fdc7f776c7a472a981121cafd17a3cd/docs/usage.md?plain=1#L36-L42

actionlintはこちらにあります。
https://github.com/VOICEVOX/voicevox_core/blob/997847fee1ec1e3e3ca48cf7d234f74d10db0113/.github/workflows/test.yml#L41-L42

@qryxip actionlint、開発側で静的解析などができなくてちょっと扱いどうしようか迷っています。
通らなくてもエラーにしないようにする（warnにする）か、READMEで案内するかとか･･･？

2023-04-25 18:36 UTC, Hiroshiba reviewed
１点以外はLGTMでした！

2023-04-25 22:07 UTC, sevenc-nanashi commented
CI通りましたー。

2023-04-25 23:09 UTC, qryxip commented on .github/workflows/build_and_deploy.yml
> +          echo "AR_$UNDERSCORED_TRIPLE=llvm-ar" >> "$GITHUB_ENV"
actionlintはエディタに統合するのが面倒ですし、確かにCIで落ちて気付くというのが大半になりそうです。

思ったのですが、<https://github.com/VOICEVOX/voicevox_core/issues/466#issuecomment-1516606529>で言ってたreviewdogをactionlintに使うというのはどうでしょうか? [reviewdog/action-actionlint](https://github.com/reviewdog/action-actionlint)というのがありますし、これをそのまま使えばよさそう。

2023-04-25 23:10 UTC, qryxip approved these changes
LGTM!

2023-04-26 02:04 UTC, PickledChair commented on .github/workflows/build_and_deploy.yml
> +          echo "AR_${TRIPLE//-/-}=llvm-ar" >> "$GITHUB_ENV"
眺めていてこの部分が気になった（多分誤植？）のですが、CI が通っているのでちょっと不思議に思っています……（私の勘違いで、元の方が正しいということでしたらすみません）

```suggestion
          echo "AR_${TRIPLE//-/_}=llvm-ar" >> "$GITHUB_ENV"
```

2023-04-26 02:05 UTC, qryxip commented on .github/workflows/build_and_deploy.yml
> +          echo "AR_${TRIPLE//-/-}=llvm-ar" >> "$GITHUB_ENV"
あ、本当だ... なんで通るんでしょうか?

2023-04-26 02:34 UTC, Hiroshiba commented on .github/workflows/build_and_deploy.yml
> +          echo "AR_$UNDERSCORED_TRIPLE=llvm-ar" >> "$GITHUB_ENV"
reviewdogを使うの良いと思います！
あとついでにwarnにしてあげれば良いかも。

2023-04-26 07:48 UTC, sevenc-nanashi commented on .github/workflows/build_and_deploy.yml
> +          echo "AR_${TRIPLE//-/-}=llvm-ar" >> "$GITHUB_ENV"
.cargo/config.tomlに書いているからだと思います。


…もしかしてこのActionなくても動く？

2023-04-26 16:28 UTC, qryxip approved these changes

2023-04-26 18:06 UTC, Hiroshiba approved these changes
LGTM！！

2023-04-26 18:07 UTC, Hiroshiba commented
マージします！

@sevenc-nanashi このアーキテクチャの製品版coreはビルドしたほうが良いでしょうか 👀

2023-04-26 18:07 UTC, merged

2023-04-26 21:05 UTC, sevenc-nanashi commented
あー、お願いしますー。

2023-04-29 05:46 UTC, Hiroshiba commented
@sevenc-nanashi ビルド完了したのでアップロードしました！！

- https://github.com/VOICEVOX/voicevox_core/releases/tag/0.15.0-preview.2