cmakeとsetup.pyを切り離す、テストの追加
VOICEVOX/voicevox_core pull request #51
Opened 2021-12-14 19:06 UTC by Yosshi999

## 内容

* これまでpip install時に自動でcmakeが走っていたが、これを取りやめてcmake buildを手動でやるようにする
* cpu版/cuda版を統一し、ダウンロードしてきたonnx runtimeがcudaに対応しているかどうかを実行時に確認するように変更
* 単体テストをgithub actionに追加

## 関連 Issue

close #50 
ref #16 : cudaをサポートしているかどうかを確認する `supports_cuda` という関数を実装したので、良さそうならこれをAPIに追加しようと思います

2021-12-14 19:07 UTC, Yosshi999 commented
ref #15

2021-12-15 05:31 UTC, Hiroshiba approved these changes
LGTM！！
良さそうに感じました！

2021-12-15 05:31 UTC, Hiroshiba commented on core/src/core.cpp
> +
将来的に似たような関数が増えそうなイメージがあります。
`supported_devices`関数にしてしまって、`{"cpu": true, "cuda": false}`みたいなjsonを返すというのはどうでしょう。

デバイスが増えたとき、関数の有無やバージョンではなく辞書のキーの有無で互換性を保てるので楽かなと思った次第です。
（`hoge`デバイスが増えたとき、`hoge`キーの有無で判定できるとか）

`devices`としましたが、cpuがcudaのことをdeviceと呼んでいいのか微妙に釈然としていません。
より良い名前があると良いのですが・・・（onnxのようにproviderと呼ぶ・・・？）

2021-12-15 05:32 UTC, Hiroshiba requested changes
あ、一箇所コメントしたからまだLGTMじゃなかった、すみません。

2021-12-15 08:34 UTC, Oyaki122 requested changes
すでに挙げられている点以外には特に問題ないと思います

2021-12-15 09:07 UTC, Yosshi999 commented on core/src/core.cpp
> +
pytorchも'cuda:0'をdeviceとして呼んだりしているのでdevicesで良いと思います

2021-12-16 04:28 UTC, Oyaki122 requested changes
API部と取得部が分割されていてとてもいいと思います
一点だけ確認をお願いします

2021-12-16 04:28 UTC, Oyaki122 commented on core/src/core.cpp
> +static std::string supported_devices_str;
この変数をグローバルにしているのにはなにか意図があるのでしょうか？
supported_devices内でしか使われていなそうなのでローカルでもいいのではないでしょうか

2021-12-16 04:39 UTC, Hiroshiba commented on core/src/core.cpp
> +static std::string supported_devices_str;
気づいたので横槍入れちゃうのですが、こうしないとstringがメモリ解放されちゃってdll使用者側でだいぶ謎の挙動をするんですよね･･･。

2021-12-16 04:42 UTC, Hiroshiba commented on core/src/core.cpp
> +      devices.cuda = true;
たしかcuda版onnxruntimeでもcpuで動くので、いまのとこ常にdevices.cpu=trueかもです。

2021-12-16 05:21 UTC, Oyaki122 commented on core/src/core.cpp
> +static std::string supported_devices_str;
ああ、なるほど確かにそうなりそうですね
それでしたらこれで問題ないと思います

@Hiroshiba ありがとうございます！

2021-12-16 07:42 UTC, Yosshi999 commented on core/src/core.cpp
> +      devices.cuda = true;
defaultで常にtrueにします

2021-12-16 07:57 UTC, Yosshi999 commented
testが落ちてますね...
pip install前にnumpyとcythonを自動で入れる方法は何かありますか？

2021-12-16 08:42 UTC, Hiroshiba commented
> pip install前にnumpyとcythonを自動で入れる方法は何かありますか？

おそらく無いです･･･。
インストールに必要なライブラリをまとめたrequirements.txtを用意するのが手っ取り早いと思います。

2021-12-16 10:57 UTC, Yosshi999 commented
あれーテストが通らない

2021-12-16 11:53 UTC, PickledChair commented
Ubuntu と Mac に関しては、Python3 のコードを Python 2.7 で走らせていて、SyntaxError で落ちているようです。engine の方のテストやビルドは Python のバージョンを 3.8 に指定して走らせているので、参考になるかもしれません。

https://github.com/VOICEVOX/voicevox_engine/blob/a451258c937113e4d244a643cbaea9d86b1fdcc1/.github/workflows/test.yml
https://github.com/VOICEVOX/voicevox_engine/blob/a451258c937113e4d244a643cbaea9d86b1fdcc1/.github/workflows/build.yml

2021-12-16 17:16 UTC, Yosshi999 commented
x86のpythonモジュールのビルドが上手くいきませんね
__imp_* (x64の命名？）のリンクに失敗してるのでbuild_extでx64のコンパイラが走っている気がするのですがよく分かりません

2021-12-16 17:51 UTC, Hiroshiba commented
テスト結果はこちらで見れそうでしょうか
https://github.com/Yosshi999/voicevox_core/actions

なるほど･･･ちょっとわかりませんね･･･
最悪、windowsの32bitを切っちゃうという手もあるのかなとちょっと思いました。

2021-12-16 19:01 UTC, Oyaki122 reviewed
build.ymlの294行目付近を
```yml
      # Build
      - if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with: 
          arch: ${{ matrix.python_architecture }}
```
とすると通りました

2021-12-17 07:59 UTC, Yosshi999 commented
全部通りました！ありがとうございます 🙇

2021-12-17 11:50 UTC, Hiroshiba approved these changes
LGTM！！
とても良いと思います！！！

2021-12-17 11:51 UTC, Oyaki122 approved these changes
LGTM!
お疲れさまでした

2021-12-17 11:52 UTC, merged