example下の"speaker_id"を、"style_id"に直す #562
VOICEVOX/voicevox_core pull request #584
Opened 2023-08-25 10:38 UTC by weweweok

## 内容

https://github.com/VOICEVOX/voicevox_core/issues/562

## 関連 Issue

ref #562 

## その他
README.mdの記載も変える必要がありますか？

2023-08-25 10:51 UTC, sevenc-nanashi commented
READMEの記述というと？

> 現在のmainブランチは工事中なので正しく動かないことがあります。バージョン0.14.4をご利用ください。

これなら消さない方がいいと思いますね、 #582 とかもありますし

2023-08-25 12:30 UTC, weweweok commented
example/python/README.mdの

ここと
https://github.com/VOICEVOX/voicevox_core/blob/e571d702b4c7e718ff1786fce0ee1892919a570d/example/python/README.md?plain=1#L55

ここです
https://github.com/VOICEVOX/voicevox_core/blob/e571d702b4c7e718ff1786fce0ee1892919a570d/example/python/README.md?plain=1#L66

2023-08-25 12:32 UTC, sevenc-nanashi commented
あ、それは更新するべきですね（`run.py -h`で出力できます）

2023-08-26 03:59 UTC, Hiroshiba commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  result = voicevox_synthesizer_tts(synthesizer,wide_to_utf8_cppapi(speak_words).c_str(),p style_id, ttsOptions, &output_binary_size, &output_wav);
> p style_id

ここ修正ミスかも？

2023-08-26 04:01 UTC, Hiroshiba approved these changes
LGTM！！

1箇所だけ多分訂正間違いがあると思うのでコメントしてみました。

2023-08-26 04:04 UTC, sevenc-nanashi requested changes

2023-08-26 04:04 UTC, sevenc-nanashi commented on example/cpp/windows/simple_tts/simple_tts.cpp
> +  result = voicevox_synthesizer_tts(synthesizer,wide_to_utf8_cppapi(speak_words).c_str(),style_id, ttsOptions, &output_binary_size, &output_wav);
```suggestion
  result = voicevox_synthesizer_tts(synthesizer,wide_to_utf8_cppapi(speak_words).c_str(), style_id, ttsOptions, &output_binary_size, &output_wav);
```

空白を入れるべきだと思います

2023-08-26 04:39 UTC, sevenc-nanashi approved these changes

2023-08-26 04:41 UTC, qryxip approved these changes
LGTM!
マージします。

2023-08-26 04:54 UTC, merged