Rust本体のバージョン更新にRenovateを利用する
VOICEVOX/voicevox_core pull request #585
Opened 2023-08-25 16:17 UTC by qryxip

## 内容

Rust本体のバージョンについてだけRenovateを導入します。

<https://github.com/VOICEVOX/voicevox_core/issues/470#issuecomment-1665868448>

動作例: <https://github.com/qryxip/play-renovate/pull/4>

## 関連 Issue

ref #470

## その他

2023-08-26 04:04 UTC, Hiroshiba commented on renovate.json
･･･あれ、もしかして特に何か導入する必要なくこのファイルを置くだけで起動する感じでしょうか 👀 
どうやって･･･？

2023-08-26 04:42 UTC, sevenc-nanashi commented on renovate.json
https://qiita.com/ksh-fthr/items/40732b6396f36c62bea2#renovate-%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

ヒホさん側でGitHub Appsを入れる必要がありそう？

2023-08-26 04:46 UTC, qryxip commented on renovate.json
です。私はGithub App版のRenovateを使いました。
 
Action版もありますが、self-hosted用途向けであり、personal access tokenが必要です。

2023-08-26 04:51 UTC, qryxip commented on renovate.json
あ、`dependencyDashboard`(デフォルト有効)がそのままでした。

このようなissueが恒久的に出続けます
<https://github.com/qryxip/play-renovate/issues/2>

2023-08-26 05:05 UTC, Hiroshiba commented on renovate.json
> +  ],
デフォルトでラベルつかないんですね。なくても良い気がしましたが、ラベルがあったほうがignore検索できそうなので、どちらかというとつけるのに賛成です。
用途を考えると、将来renovate以外の何かに移行したときにラベルを変えないようにするためにもうちょっと汎用的な名前でも良いかもと思いましたが、まああまり考えても意味ない気がするのでこの名前で良いのかなと思いました。

2023-08-26 05:05 UTC, Hiroshiba commented on renovate.json
とりあえずデフォルト設定に従っておきつつ、邪魔そうだったら消すのが良さそうに感じました。

2023-08-26 05:06 UTC, Hiroshiba commented on renovate.json
なるほどです。Github Appsの導入を考えようと思います。

2023-08-26 05:11 UTC, Hiroshiba approved these changes
LGTM！！

マージ後、このリポジトリのみに対してRenovate Github Appを導入してみようと思います。
（たぶん導入したリポジトリに対して自動的に発動するっぽいので、とりあえずこのリポジトリだけ対象に。）

メンテナ共有です 🙏  @y-chan

2023-08-26 05:28 UTC, qryxip commented on renovate.json
> +  ],
思ったのですが、excludeするなら`-author:app/renovate`でできると思うので、ラベルは要らないかもしれません。

2023-08-26 05:35 UTC, qryxip commented on renovate.json
> +  ],
あとPCブラウザでRefined GitHubを使っているなら[dim-bots](https://github.com/refined-github/refined-github/blob/f8afe36f6a588982f18580418754d0ef535ecfa0/source/features/dim-bots.tsx)があるので、フィルター無くてもそんなにノイズが無いかもしれません。

![image](https://github.com/VOICEVOX/voicevox_core/assets/14125495/8c683067-ce39-47ec-aa52-7057543c37e4)

2023-08-26 05:45 UTC, Hiroshiba requested changes

2023-08-26 05:45 UTC, Hiroshiba commented on renovate.json
> +  ],
あ、このプリセット、存在しないかも･･･？

2023-08-26 05:45 UTC, Hiroshiba commented on renovate.json
> +  ],
> 思ったのですが、excludeするなら-author:app/renovateでできると思うので、ラベルは要らないかもしれません。

なるほどです。シンプルに始めるのが良さそうに思うので、ラベルは無しのほうが良いかもです。

2023-08-26 06:29 UTC, qryxip commented on renovate.json
> +  ],
`config:recommended`にリネームされたようです。

<https://github.com/renovatebot/renovate/blob/b8823e3debe08a02b627f835a1f9a209547b5927/lib/config/presets/common.ts#L17>

[`0c6eeaa` (#585)](https://github.com/VOICEVOX/voicevox_core/pull/585/commits/0c6eeaa435aa194fa3286a8fb9c9566485214156)

2023-08-26 06:30 UTC, qryxip commented on renovate.json
> +  ],
ラベル無しにしました。

[`d2e469f` (#585)](https://github.com/VOICEVOX/voicevox_core/pull/585/commits/d2e469fec2656a5b35e359662f6e2bbea6782a68)

2023-08-27 16:46 UTC, Hiroshiba commented on renovate.json
> +  ]
こちら何か資料を参考にされましたか？ 👀 
メモっておけばメンテする時の参考になるかなと。

2023-08-27 16:46 UTC, Hiroshiba reviewed
たぶん問題ないと思うのでマージします！！

2023-08-27 16:46 UTC, merged

2023-08-27 17:03 UTC, Hiroshiba commented
とりあえずRenovateを導入してみました。

Renovate側の今の表示はこんな感じです。
![image](https://github.com/VOICEVOX/voicevox_core/assets/4987327/3dd39555-d75d-453d-997f-a4804bd0bf0e)

RenovateのGithub Appの設定はこんな感じです。
![image](https://github.com/VOICEVOX/voicevox_core/assets/4987327/8df6436b-b364-40a5-834b-cedd3fff0899)

2023-10-06 17:09 UTC, qryxip commented
3ヶ月経ってRust 1.72.0と1.72.1と1.73.0が出ましたが、作動してませんね。<https://github.com/qryxip/play-renovate/pull/4>には毎回来ているのですが...

![image](https://github.com/VOICEVOX/voicevox_core/assets/14125495/d8025ca8-2380-40bf-a3d1-3498e60eb40d)

Dashboardも作られてないし、Renovate自体が動いてなさげ?

2023-10-07 02:20 UTC, Hiroshiba commented
なるほどです。
Renovate自体が動いてないことを確認するにはどうすれば良い感じでしょうか･･･？

2023-10-07 02:23 UTC, Hiroshiba commented
あ、こちらのissueで良さそうかも。

- https://github.com/VOICEVOX/voicevox_core/issues/470