ONNX Runtimeとモデルのシグネチャを隔離する
VOICEVOX/voicevox_core pull request #675
Opened 2023-11-05 18:31 UTC by qryxip

## 内容

ONNX Runtimeとモデルのシグネチャ(?)の存在を、別のモジュールに分離します。

以下の改革の前準備です。

<https://github.com/VOICEVOX/voicevox_core/pull/553#issuecomment-1656366892>

## 関連 Issue

#545

## その他

2023-11-06 12:33 UTC, Hiroshiba commented
なかなか巨大になりそうですね…！！
お待ちしてます！！

2023-11-06 18:12 UTC, qryxip commented
大体考えて組んだので、draftを外します。

モジュール`infer`の登場人物は主に3つに分けられます。これらをもとに抽象化を組んでいます。
(ただinfer.rsは115行しかないといっても、中身の圧が強いのでファイル分割すべきかもしれません)

- `trait InferenceRuntime` (e.g. `Onnxruntime`)
    - `trait Session`
    - `trait RunBuilder`
    - `trait InputScalar` (e.g. `i64`, `f32`)
- `trait Signature`
    - `trait Output`
    - `enum SignatureKind` (= `PredicutDuration | PredicutIntonation | Decode`)
        - `struct PredicutDuration: Signature<Kind = SignatureKind>`
        - `struct PredicutIntonation: Signature<Kind = SignatureKind>`
        - `struct Decode: Signature<Kind = SignatureKind>`
- `struct SessionSet<K (= SignatureKind), R: InferenceRuntime>`
    - `struct SessionOptions`

補足としては:

- onnxruntime-rsを触る部分はまとめて`crate::infer::runtimes::onnxruntime`に隔離しました。
- `model_file`モジュール (復号部分), `SessionOptions`, `SessionSet`, `InferenceModels`などは`infer`モジュールに移しました。
    - `status::SessionSet`と`voice_model::InferenceModels`は[enum-map](https://docs.rs/enum-map/3.0.0-beta.1/enum_map/index.html)クレートを用いて`EnumMap<SignatureKind, …>`のような形で表現しています。
- `<R: InferenceRuntime>`の型引数は`SynthesisEngine`のあたりで止めています。また`SignatureKind` (= `PredicutDuration | …`)も`status`モジュールに直接登場させています。
- 将来の変更に対する耐性としては、次のように考えています。
    - ONNX Runtime以外のランタイム(e.g. TFLite)を導入するときは、`crates::infer::runtimes`に新しいランタイムを増設します。
        - featureを導入し、コンパイル時にONNX Runtimeと切り替えられるようにします。
        - ただVVMの仕様も含め、パブリックAPI部分の変更はそもそもどのみち避けられないかと思います。
    - モデルのシグネチャや数を変更するときは、`crate::infer::signature`を変更します。
        - `([f32],)`以外の出力にするときは、infer/runtimes/onnxruntime.rsの`impl Output<Onnxruntime> for (Vec<f32>,)`の部分を拡張します。
        - predict部分のモデルとdecodeのモデルを別々に分けて読み込みたい、という需要が将来発生した場合、`enum SignatureKind`の存在を二つに分割してそれぞれについて`EnumMap`を管理します。
        - 3-モデルの組と4-モデルの組を同時に扱いたいとなったときも`enum SignatureKind`を複数作って抽象化します。

2023-11-07 00:26 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
`InferenceRuntime`や`Session`や`Signature`がありますが、prefixに`Inference`をつけるかつけないかを統一してもいいかもと思いました！
けどまあ名前衝突とかあまりなさそうだし、このままでも別にいいかも。

2023-11-07 00:51 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/runtimes/onnxruntime.rs
> +}
一般的にビルダーパターンは、最後に`.build()`とかで1つのインスタンスを作る物を指すと思います！
HogeBuilderは.build()でHogeインスタンスを返す、みたいな。
なので`InputBuilder`にして`.input()`関数を`.build()`にすると一般的なビルダーパターンになるかなと。

でも多分やりたいことはそれではなく、inference(run)に必要な加工をする、みたいな感じですよね。
うーーーーーーーーん。。。どういう名前がいいんだろう････。`Adaptor`とか･･･？

2023-11-07 01:09 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/runtimes/onnxruntime.rs
> +}
Inputは`RunBuilder`で変換されるのに対し、OutputはOutput.runで変換していて対称性がないように感じました！
あと`Output`というデータ構造のみを持ちそうな名前のクラスが`run`メソッドを持つのもちょっと違和感ありました。

個人的には`RunBuilder`を`Adaptor`にしてinput/outputの変換どちらも担わせるか、`Signature`ごとにinput/outputの変換関数をもたせるのが良いかなとか思いました！

2023-11-07 01:21 UTC, Hiroshiba reviewed
見渡しました！
input/outputの加工用関数の非対称性が気になりましたが、全体的に良い感じなのかなと思いました！

2023-11-07 14:44 UTC, sevenc-nanashi reviewed
ヒホさんと同意見ですー。

2023-11-08 18:46 UTC, qryxip commented
色々再構成しました。
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/e0f29c649df39a4006a47c8813208ac9232cb9d1>
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/cb1db348ab43b01b542c6404e6c0283e9aae251b>

- `trait InferenceRuntime`を継承する次の3つのトレイトを導入し、これらに役割を持たせました。
    - `trait SupportsInferenceInputTensor<I>` (`I`の例: `Array1<i64>`)
    - `trait SupportsInferenceInputTensors<I>` (`I`の例: `PredictDurationInput`)
    - `trait SupportsInferenceInputOutput<O>` (`O`の例: `(Vec<f32>,)`)
- `trait Signature`を`InferenceSignature`と`InferenceInput`に分離しました。また`trait InputScalar`と`trait Output`は、上記の`InferenceRuntime`のサブトレイトに吸収される形で消えました。 (<https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1384224966>)
- `RunBuilder`は(基本的に)自分で関数を持たなくなったので、`RunContext`としました。(<https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1384216221>)
- `RunContext`を除きprefixに`Inference`を付けるようにしました。(<https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1384216221>)

2023-11-09 00:46 UTC, Hiroshiba reviewed
ほぼLGTMです！！

コードの読み方がわかりました。onnxruntime.rsを読んで、signature.rsを読んでからinfer.rsを読むとわかりやすいですね！

ドキュメントを作っておかないと迷子になりそうだなと思いました。
と言っても大層なものは必要なくて、infer.rsのそれぞれのtraitやimplに1行ずつ目的を書いていくだけでだいぶ変わるかなと！

あと、実装レビューの前に設計レビューをすると良かったかもとか思いました。

今まではonnxruntime周りが煩雑だったがゆえに、変更が生じても適当に書き足せば良かったのですが、今回で理路整然となるので、追加の実装をしたいときにどこに足せば良いか分からなくなるだろうなと思いました。
project-sなどで関数を追加したり形を変えたりすることがちょっとありそうですが、その際は相談させていただけると･･･！！

2023-11-09 00:46 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
このtraitの目的は、Outputのサポートではなく、型Oの隔離と考えると分かりやすいように感じました。
実際やってることはsession.runの型付けなので。
名称を`InferenceRuntimeForOutput`にして`InferenceRuntime`の近くに置くとかどうでしょう。
そうするとInputとの対称性も分かりやすいかなと。
あまり強い意見じゃないです。そのままでもまあ！

というより、真に必要なのはドキュメントかもしれない･･･。

2023-11-09 00:46 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +    fn input(input: I, ctx: &mut Self::RunContext<'_>);
inputという動詞が使われているのが若干違和感あるかもです。
`process_input`とかのが分かりやすいっちゃ分かりやすいのですが、まあ長いよなぁとも思います。
こちらもあまり強い意見じゃないです。そのままでもまあ！

ちなみに、このあたりよくわかってないのですが、fromとかtoを使ったりとかは難しい感じでしょうか。

2023-11-09 13:05 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +    fn input(input: I, ctx: &mut Self::RunContext<'_>);
ここですが、`make_run_context(sess: &mut Self::Session, input: I) -> Self::RunContext<'_>`という型にしてみました。
他の`fn input`は`push_input`と`with_input`にしています。
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/fbd7d1c8016e0e0d7bdc31b064a5e44d21b41f76>

2023-11-09 13:21 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
その名前だと`RuntimeForInputSignature`と`RuntimeForOutput`が排他であるという印象を与えないかと思いました。

2023-11-09 13:29 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
ところでtflite-rs (およびTFLite)自体を見たのですが、任意次元の入出力はどうやら普通にできそうに見えました。

考えたのですが、ランタイム全部が任意次元任意個数の入出力が行えると仮定できるなら、これらの`Supports`系は本体(`InferenceRuntime`)に統合できると思います。
仮に今後、扱える型が制限されたランタイムを導入するにしても、モデル内での型/次元変換を「元に戻す」操作の抽象化を`InferenceRuntime`下に上手く構築できそうな気がします。

2023-11-09 13:46 UTC, qryxip commented on crates/voicevox_core/src/infer/signatures.rs
> +}
ところで{`predict_{duration,intonation}`, `decode`}のセットって、project-sとかと区別する形で何か名前は付いてますか/付ける予定はありますか?
(ここの名前を`PiPdD`とか`TwoPhasePrediction`とかにしたい気持ちがあります)

2023-11-10 01:54 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
うーんなるほどです。
一般的な設計じゃないとは感じますが、まあここ辺りがそのままAPIとして露出することはないと思うので、仮に問題があってもそこまで大した問題ではないと考えると、まあ特にFIXMEコメントもなくていいのかなと思いました！

2023-11-10 03:12 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
> その名前だと`RuntimeForInputSignature`と`RuntimeForOutput`が排他であるという印象を与えないかと思いました。

まあよくよく考えるとRuntime全てが複製されているように感じるので何か変だなと思うようになりました！

> 考えたのですが、ランタイム全部が任意次元任意個数の入出力が行えると仮定できるなら、これらの`Supports`系は本体(`InferenceRuntime`)に統合できると思います。

それが可能なのであれば良さそうだなと思います！
少なくともonnxruntimeでは可能で、そちらの方が小さく始められそうなので、可能ならそちらの方がいいのかなと。

2023-11-10 03:24 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/signatures.rs
> +pub(crate) enum InferenceModelKindImpl {
この辺りの用語に関して共有です！

inferenceはmodelと1対1対応するかどうかは、僕たちの定義に寄るというイメージです。
model１つを使って値を１つ出すことをinferenceと呼ぶようにすれば違和感なさそうです。
この定義自身も僕は違和感ないです。

TTSする一連の流れ（PredictDurationして、PredictIntonationして、Decodeする）もまあ元の定義的にはinferenceと呼べるので気をつけねば、みたいな感じです！

2023-11-10 03:27 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/signatures.rs
> +}
ちょっとどうしていくか決まってなくて難しいという実状があります。
project-sの機能を使ってTTSすることが可能で（喋るボカロみたいな）、需要もありそうなんですよね･･･。

ということで、どのまとまりにするのが良いのか現段階でわからない感じかなと。

2023-11-10 03:38 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
すみません今気づいたのですが、`with_input`はパラメータが足りなかった場合でもおそらく謎の初期値で実行されてエラーが帰ってこない課題がありそうに感じました。
新しくシグネチャを追加した際パラメータが足りてないことに気づくのが遅れたりしてしまうかもで、可能なら検査可能になっていて欲しいかもです。

コンパイル時に気づけると嬉しいですが、実用上実行時でも良いかなと思いました。
（must/should/want/canのshouldくらいのイメージ）

2023-11-10 15:37 UTC, qryxip commented on crates/voicevox_core/src/infer/signatures.rs
> +}
なるほど。では今は`…Impl`のままにしようと思います。

2023-11-10 15:44 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
確かにそれは不味いですね。ここら辺の宣言を(proc-)macro化することを考えてみます。

2023-11-10 15:58 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
> それが可能なのであれば良さそうだなと思います！
少なくともonnxruntimeでは可能で、そちらの方が小さく始められそうなので、可能ならそちらの方がいいのかなと。

分かりました。ではそのようにします。
(tflite-rsや[ort](https://docs.rs/ort)などとは異なり現状のonnxruntime-rsは中途半端な仕様になっているので、実装はちょっと膨らむかもしれませんが)

2023-11-10 16:27 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
1回マージでも大丈夫です。やりやすい方で！

2023-11-11 04:36 UTC, qryxip commented on crates/voicevox_core/src/infer/signatures.rs
> +pub(crate) enum InferenceModelKindImpl {
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/c40afd578a2c1231598d2cc6563f7f3c2050b6db>
しました。`InferenceModelGroup`は`InferenceGroup`としています。

2023-11-11 04:37 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/81b5804037ea21fe0b3fe0ae934fe1d2a2548c74>
また色々変わってしまいましたが、`Supports…`系を排しました。

2023-11-11 04:37 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390123290>
- <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390123345>

2023-11-11 08:03 UTC, Hiroshiba reviewed
ちょっとレビューしてみました！

2023-11-11 08:03 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +    const INFERENCE: <Self::Group as InferenceGroup>::Kind;
（細かいことですが）ここはKINDのがわかりやすいかも

2023-11-11 09:00 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/120106b8d38d4430d7b64b3720fb78ec1a7d09e8>
crates/voicevox_core_macrosを作成し、signatureの実定義周りをマクロ化しました。

2023-11-11 09:05 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +pub(crate) enum AnyTensor {
例えばTFLiteでは"tensor"という言葉がAPIに出てくるので、区別できるような名前にしたかったためprefixを付けました。

ただAnyというのも性質は示しても役割は示していないので、 `OutputTensor`にしてみました。

<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/590ce48f0de3b2052518a5204f89ee53774d1b10>

2023-11-11 09:06 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +    const INFERENCE: <Self::Group as InferenceGroup>::Kind;
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/c4d5ebe3157126fb03253d404aa3177f0fbf195c>

ところで今変更して思ったのですが、`trait InferenceSignature`って、単に`trait Inference`にしてもよいような気がしました (`InferenceInputSignature`は`InferenceInputSignature`のままで)

2023-11-11 09:08 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/120106b8d38d4430d7b64b3720fb78ec1a7d09e8>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390182673>
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/590ce48f0de3b2052518a5204f89ee53774d1b10>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390183588>
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/c4d5ebe3157126fb03253d404aa3177f0fbf195c>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390184378>

2023-11-11 11:55 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/1b1b7bfc32d7b7d21cc98cbf219046fc257d75bd>: `status`モジュールを`infer`モジュール下に移しました。それに加え、`InferenceGroupImpl`の存在を`Status`から外し、`Status<R: InferenceRuntime, G: InfereceGroup>`として運用するようにしました。`Synthesizer`の四層構造について以前、二層まで圧縮できるのではないかと言った気がするのですが、`Status`がこういう役割を果たせることがわかったので今は三層(`Synthesizer` → `InferenceCore<R>` → `Status<R, G>`)で十分かなと思っています。
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/c39f48cb5c560b6f4dde212767ba78beba941606>: `trait RunContext`を削除しました (`InferenceRuntime::RunContext`はそのまま)

2023-11-11 13:17 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
`onnxruntime::session::Sesssion::run`が`TypeToTensorElementDataType`を要求するため、`InputScalar`の親に置かないといけないためですね。

一応onnxruntimeを"feature-gate"して切り替えることを念頭に置いてはいます。

2023-11-11 13:52 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
"kind"と"group"と呼び名を分けておきたいと思っていたのですが、"kind"を直接"group"と呼んでも問題無いことに気付いたので、ここを潰してみました。

(例えば数値型に対して`Ring`とか`Group`とか`Field`というくくりでtraitを宣言したりするといったことは行なわれているので)

2023-11-11 13:55 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/c316209419cc81f96d16739ac10aaba1c6a907d1>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390230606>

2023-11-12 02:03 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/2274a34d1382a4c528228c5caa63c2f5cdad7b35>

sessionのロード時に、"signature"とsessionが覚えている入出力情報と付き合わせて違っていたら弾く機構を入れました。違っていたらこのようなエラーになります。

```
Error: expected {phoneme: int64_t[], speaker_id: int64_t[]}, got {phoneme_list: int64_t[], speaker_id: int64_t[]}
```

2023-11-12 02:04 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/2274a34d1382a4c528228c5caa63c2f5cdad7b35>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390316946>

2023-11-13 01:04 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/b7d48f3ab8cc7747f8c72561837ca7b84bcfb872>

signature.rsのボイラープレートをあらかたマクロ化しました。signatures.rsは今75行です。

2023-11-13 01:04 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/b7d48f3ab8cc7747f8c72561837ca7b84bcfb872>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1390535215>

2023-11-13 15:30 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +    const INFERENCE: <Self::Group as InferenceGroup>::Kind;
そこだけ見ると良さそうなのですが、`InferenceGroup`というのがあって、そちらは`InferenceSignature`のグループではないので、他の構造との兼ね合いがなんかややこしそうだなと感じました！
とりあえずここはResolveにしますね

2023-11-13 15:45 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
なるほどです。
ちょっとわかってないのですが、概念Aを継承している概念Bがあったとして、AがBを知ってしまってる状態になっているのかなと思ってます。
実装上よくないけどとりあえずこうなっている、というのは全然許容できると思うので、それがわかるようなコメントが書かれていれば良いのかなと思いました！

2023-11-13 18:25 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
Kindとしての機能を持っていた部分（MapのValueの値とか）がGroupという名前になってしまって、GroupのMapを持っているかのような錯覚を受ける実装がちらほら見られました！
↓とか。
```rs
struct LoadedModels<R: InferenceRuntime, G: InferenceGroup>(
    BTreeMap<VoiceModelId, LoadedModel<R, G>>,
);
```
Groupやkindという属性を書いてしまうと、その逆の使用した時にややこしいことになると気づきました。
`Error`みたいな感じでどちらにも属さないような名称をつけると良さそうかも？

となると`PredictDuration`とかが属しているものの名前を考えないといけないのですが･･･。
`ModelFlow`や`InferenceModel`、あとは造語で`InferenceDomain`とか`Operation`（工程）とかどうでしょう。
個人的には`Operation`はありかなぁと思いました！

2023-11-13 18:28 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +    const OUTPUT_PARAM_INFOS: EnumMap<Self, &'static [ParamInfo<OutputScalarKind>]>;
この2つの情報はサブ的な目的かなと思うので、そうとわかるようにコメントかプライベートっぽい名称（`__`を最初につけるとか）にするのはどうでしょう？

2023-11-13 18:29 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +pub(crate) enum InputScalarKind {
Kindというより完璧に型なので`InputScalarType`でも良いかも？

2023-11-13 18:32 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +    fn extract(tensor: OutputTensor) -> std::result::Result<ArrayD<Self>, ExtractError>;
（細かいですが）
Inputの処理は`Runtime`内にあるのに対し、Outputの処理は`Output`内にあるのがちょっとだけ気になりました。

2023-11-13 18:36 UTC, Hiroshiba commented on crates/voicevox_core_macros/src/lib.rs
> +pub fn derive_inference_group(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
さすがにこのマクロ群はドキュメントコメントがないと何もやっているものなのか推測が難しく、メンテ不可能になりそうかもとちょっと思いました。

2023-11-13 18:38 UTC, Hiroshiba approved these changes
読んでみました！！
コメントを色々してはいるのですが、少なくとも機械学習モデルを使う上で大きく問題が発生するような箇所はないと思います。

であれば、もう一旦マージして、階層構造を小さくすることに取り組むのが良いのかなと思いました。
実装していく上でまた新しい課題が見つかったりもする可能性も全然あると思いますし。

構造の変更はもうこのプルリクエスト内ではやめて、名称の変更やドキュメントの追加だけにして、次に進むというのはどうでしょう･･･？
（1回のレビューに3時間かかっており。。。。）

2023-11-13 18:38 UTC, Hiroshiba requested changes
（間違えてapproveしてしまいました 🙇 ）

2023-11-14 15:02 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/96a93e9f16c8b0b9e3ea01083bfe42790993dcd4>

考えたのですが、`InferenceDomain`にしました。それに伴い、signatures.rsをdomain.rsにリネームしました。

`Operation`だと「モデル一つの操作」をイメージしてしまわないかと思ってしまいました。

2023-11-14 15:04 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +    const OUTPUT_PARAM_INFOS: EnumMap<Self, &'static [ParamInfo<OutputScalarKind>]>;
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/c654cd1f2d10acbc3f68aa4e6694525d4566beb2>

`__`も考えたのですが、status.rs内で使っていることを考えるとやめた方がよいかなと思いました。docstringを書く方にしました。

2023-11-14 15:05 UTC, qryxip commented on crates/voicevox_core_macros/src/lib.rs
> +pub fn derive_inference_group(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/868d3f61e76cf04147674c86d60142c7fec0ca6b>

書きました。

2023-11-14 15:06 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/099879375df892544a95825832197b51a3863ba0>

visitor pattenを組めばいけるのでは? というのが浮かんだため、FIXMEコメントとして残しました。

2023-11-14 15:12 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/96a93e9f16c8b0b9e3ea01083bfe42790993dcd4>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1392739314>
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/59d87797ca64e39375c48cb4413a6be3f8d1cbfa>: voicevox\_core\_macrosのリファクタ(モジュール分割)をしました。
    200行以上のコードのインデントのずれが生じるため、今やった方がよいかなと…
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/d0dc56ff96cec6652540016343aa9c47ffc1c819>: `InferenceDomain::{INPUT,OUTPUT}_PARAM_INFOS`を統合し、タプルの`EnumMap`にしました。
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/c654cd1f2d10acbc3f68aa4e6694525d4566beb2>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1392743606>
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/868d3f61e76cf04147674c86d60142c7fec0ca6b>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1392744183>
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/099879375df892544a95825832197b51a3863ba0>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1392746394>

2023-11-14 15:24 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +    fn extract(tensor: OutputTensor) -> std::result::Result<ArrayD<Self>, ExtractError>;
実装はインスタンス型ごとなので、ここじゃないと駄目かと思います。

`Input`の方は`Runtime`ではなく、`onnxruntime::TypeToTensorElementDataType`みたいなトレイトで動いている形ですね。
(`Input`については<https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1392746394>というのを考えています)

2023-11-14 15:29 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +pub(crate) enum InputScalarKind {
ここは型(type)ではなく値(kind)だと思っています。

リネームするにしても<code>Data**t**ype</code> (`DataType`ではなく)かなと思うのですが、`InputScalar`からのつながりが不明瞭にならないかと思いました。

2023-11-14 15:37 UTC, qryxip commented
> であれば、もう一旦マージして、階層構造を小さくすることに取り組むのが良いのかなと思いました。 実装していく上でまた新しい課題が見つかったりもする可能性も全然あると思いますし。
>
> 構造の変更はもうこのプルリクエスト内ではやめて、名称の変更やドキュメントの追加だけにして、次に進むというのはどうでしょう･･･？ （1回のレビューに3時間かかっており。。。。）

はい。それがよいと思います。

階層構造ですが、「入出力のworkaround処理」をdomain.rs(旧signatures.rs)に移せればこんな感じにできるのではと思っています。

```
synthesizer.rs --+--> infer/status.rs
                 +--> infer/domain.rs (旧signatures.rs)
                 +--> infer/runtimes/
                 |
                 +--> open_jtalk.rs
```

2023-11-14 15:43 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
一旦良さそうに感じました！！resolveします！

2023-11-14 15:50 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +    fn extract(tensor: OutputTensor) -> std::result::Result<ArrayD<Self>, ExtractError>;
インスタンス型というのはちょっとわかってないのですが、Signature（Domain）（Session）ごとということでしょうか。
であればSessionとかに書くのが良いのかなと思いました。

そもそも違和感があるのがInputとOutputの処理系列の非対称性なんですよね。
逆操作をしているはずなので同じような処理系統にできるはずなのにそうなってないのが不思議だなと。
A→Bには`TypeToTensorElementDataType`、B→AにはOutputScalar.extractと非対称に見えてる感じです。

まあでもコメントの目的としては違和感があるということを伝えるのが主なので、別に変更は今なくてもいいのかなと思いました。
ということでResolve！

2023-11-14 15:53 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +pub(crate) enum InputScalarKind {
うーん、なるほどです。
まそこまで強い意見ではなかったので、Resolveデータの

2023-11-14 16:09 UTC, Hiroshiba commented
> こんな感じにできるのではと思っています。

なるほどです、良さそうに思いました！！

なんとなくの直感ですが、statusがかなり多くの責務を担いそうだなと思いました。statusという名称が曖昧なので便利屋さんみたいになりがちかも。将来なんか名前変えられると良さそう！
あとSynthesizerが何を見れるべきかを考えていくとアーキテクチャ作りやすいのかなとか思いました。RuntimeやSessionは見れるべきではない、など？

2023-11-14 16:54 UTC, Hiroshiba reviewed
ほぼLGTMです！！

Domainのとこだけ落としどころが見つかれば完成なのかなと思いました！！

2023-11-14 16:54 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +    const KIND: Self::Domain;
ちょっとわからないですが、`KIND`やめて`DOMAIN`でも良いかも？

2023-11-14 16:54 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/domain.rs
>  pub(crate) enum InferenceKind {
せっかくDomainという言葉を定義したのでそれを使うのが良さそう。
ここはもうVOICEVOX専用なので、一旦`VoicevoxInferenceDomain`とかでも良いかもとか思いました。
（他のDomainがないので名称がつけられない･･･。）

2023-11-14 16:54 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/status.rs
> +impl<R: InferenceRuntime, D: InferenceDomain> Status<R, D> {
Rustの慣習をちょっとわかってないのですが、R/DをRuntime/Domainにすると読みやすいかもとか思いました！
（数百行という広範囲にわたって使われるジェネリクスで、かつDがDimensionと被りそうなので、くらいの気持ちです）

2023-11-14 16:54 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/status.rs
>              .map(|(k, m)| {
kだったりdだったりで表記が混じってるかもです！

2023-11-14 16:54 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +}
すみませんちょっと誤解があったのでコメントです！

Domainは１つの操作（PredictDuration）を意味しているのだと思っていました。
複数の全操作をまとめてDomainと呼ぶ感じなのかなと別のとこのコードを読んでいて思いました。

ニコ生コメントで、Domainをtrait Domain / enum Operationに分けるのはどうかというディスカッションをしたので、メモです！
（いったんunresolveにします）

2023-11-14 17:32 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/75fd7acaa6a4d03f67552ca3d80e0253da88b8fd>

`Domain`と`Operation`への分離をしました。

```rust
pub(crate) enum InferenceDomainImpl {}

impl InferenceDomain for InferenceDomainImpl {
    type Operation = InferenceOperationKind;
}
```

2023-11-14 17:34 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/75fd7acaa6a4d03f67552ca3d80e0253da88b8fd>: <https://github.com/VOICEVOX/voicevox_core/pull/675/files/81b5804037ea21fe0b3fe0ae934fe1d2a2548c74#r1392976600>

2023-11-14 17:35 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +    const KIND: Self::Domain;
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/75fd7acaa6a4d03f67552ca3d80e0253da88b8fd>にて`OPERATION`にしてあります。

2023-11-14 20:33 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/status.rs
> +impl<R: InferenceRuntime, D: InferenceDomain> Status<R, D> {
良いと思います！
まあRでも…！

2023-11-15 00:05 UTC, qryxip commented on crates/voicevox_core/src/infer/status.rs
> +impl<R: InferenceRuntime, D: InferenceDomain> Status<R, D> {
あ、コメントの意図を勘違いしていました。慣習としては余程のことがない限りは一文字を超える型引数ってまず見ないですね。そしてその余程よりはまだ余裕があるかなと思っています。

2023-11-15 01:24 UTC, qryxip commented on crates/voicevox_core/src/infer/status.rs
> +impl<R: InferenceRuntime, D: InferenceDomain> Status<R, D> {
↑ なんでそんな慣習なのか考えたのですが、やはり具体型と区別するためなのかなと思っています。[関連型](https://doc.rust-lang.org/stable/reference/items/associated-items.html)や[ライフタイム引数](https://doc.rust-lang.org/stable/reference/trait-bounds.html#lifetime-bounds)はコード上そうであることが明らかなのですが、型引数は具体型と同じ名前空間に存在しちゃってるのが大きいのかなと。

2023-11-15 16:04 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +}
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/ad222c98cd1e47a4dbb920d742bf2844bf3cd442>

`InferenceOperationImpl`のつもりで`InferenceOperationKind`としていたため、`InferenceOperationImpl`にしました。

2023-11-15 16:04 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/ad222c98cd1e47a4dbb920d742bf2844bf3cd442>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1394423004>

2023-11-15 16:29 UTC, Hiroshiba commented on crates/voicevox_core/src/infer/status.rs
> +impl<R: InferenceRuntime, D: InferenceDomain> Status<R, D> {
なるほどです。もう表記余ってないですもんね。
1文字が良いのかなと思いました！

2023-11-15 16:36 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +pub(crate) trait InferenceOperation: Copy + Enum {
この2つだけはVOICEVOX独自の概念なのでドキュメントを追加してあげておくと混乱を避けられるのかなと思いました！

InferenceOperationは、関心のある推論処理･･･？
InferenceDomainは`InferenceOperation`の集合･･･？
ちょっとずばりとは思いつきませんでした。。

2023-11-15 16:44 UTC, Hiroshiba commented on crates/voicevox_core_macros/src/inference_domain.rs
ファイル名operationかも？
（ちゃんとわかってないので的外れのコメントかも）

2023-11-15 16:46 UTC, Hiroshiba commented on crates/voicevox_core_macros/src/lib.rs
> +/// pub(crate) enum InferenceOperationKind {
（とても細かいですが気がついてしまったので）
Implかも？

2023-11-15 16:51 UTC, Hiroshiba approved these changes
LGTM！！！！！！

お疲れ様でした！！！！
良い切り分けができたのではないかなと思います！！！

Interfaceの設計をレビューするということに慣れておらず、右往左往してしまってすみませんでした 🙇 
（コードがある場合は、先に実装を見て書き心地を把握し、ドメイン用語の認識をそろえて、設計方針の認識を揃えていくのが良さそうだと思いました！）

一気に多層構造も切り崩せると嬉しいですね！！！

2023-11-15 23:32 UTC, qryxip commented on crates/voicevox_core_macros/src/inference_domain.rs
「`voicevox_core::infer::domain`に対するマクロ」、みたいな意味合いです。

2023-11-15 23:55 UTC, qryxip commented on crates/voicevox_core_macros/src/lib.rs
> +/// pub(crate) enum InferenceOperationKind {
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/7005c96a74cb49789eaf07d7e2411163fca09bbc>

2023-11-15 23:56 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +pub(crate) trait InferenceOperation: Copy + Enum {
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/a73f22c3a4dc76ea93d3af6b9003d71fc25659ae>, <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/f17919b694ac29cbea4a8e3caaad900d77feeebd>

こんな感じに書いてみました。

2023-11-15 23:59 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/7005c96a74cb49789eaf07d7e2411163fca09bbc>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1394995277>
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/94179921a7d34d324df61d3b047f3dfff410e66b>: Merge branch 'main' into HEAD
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/1655719e178680e66b1ea6baa2fa3150f42949c5>: doc内の「`voicevox_core`内の」という表現を「Rust APIクレート内の」と置き換えました。
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/a73f22c3a4dc76ea93d3af6b9003d71fc25659ae>, <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/f17919b694ac29cbea4a8e3caaad900d77feeebd>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1394995786>

2023-11-16 00:17 UTC, Hiroshiba commented on crates/voicevox_core_macros/src/inference_domain.rs
なるほどです！！

2023-11-16 00:19 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +pub(crate) trait InferenceOperation: Copy + Enum {
あ、書きかけ…

2023-11-16 00:20 UTC, Hiroshiba commented on crates/voicevox_core/src/infer.rs
> +/// `VoiceModel`に対応する、
脱字かもです！

2023-11-16 01:18 UTC, qryxip commented on crates/voicevox_core/src/infer.rs
> +/// `VoiceModel`に対応する、
<https://github.com/VOICEVOX/voicevox_core/pull/675/commits/48bdb1b74470eca0fd2ce033459dedbb6700d9af>

書きました。

2023-11-16 01:24 UTC, qryxip commented
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/48bdb1b74470eca0fd2ce033459dedbb6700d9af>: <https://github.com/VOICEVOX/voicevox_core/pull/675#discussion_r1395041306>
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/9d7d001b81482fd31a29304766c5c4274c82b46d>: 二重説明になっていた箇所を削除
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/af828eb943b1b43542648ac8c7280d3001591c89>: 不要な修飾を削除
- <https://github.com/VOICEVOX/voicevox_core/pull/675/commits/b6b7975278b396ad6bbc225ab98b6185830c3613>: マクロの中でのみ使っている`ArrayExt`を、マクロの中に押し込める

2023-11-16 02:48 UTC, Hiroshiba commented
修正確認しました！！マージします！！！

2023-11-16 02:48 UTC, merged