READMEのサンプルを、製品版のものを実行する用途のコードに変更する
VOICEVOX/voicevox_core pull request #68
Opened 2022-01-21 15:52 UTC by Yosshi999

## 内容
現状のサンプル実行手順を「コアライブラリのビルド」に移し、代わりに製品版(releases)を利用する方法に変更しました。

## 関連 Issue
close #66 

## その他
手でコピーする作業がいくつかあるが自動化すべきか？

2022-01-21 16:35 UTC, Oyaki122 requested changes
PRありがとうございます
編集された範囲ではないのですが、少し変更していただきたい箇所があります

今回サンプル実行とビルドを分けたことで、「依存関係」のところにonnxruntimeとcmakeが合わせて書かれていることが文章を読みづらくしているかと思います
そこで、現在の「依存関係」の項目を「onnxruntimeのダウンロード」などに改称し、cmakeについては現在の位置からは削除して、ビルドの方でインストールを促すのはどうでしょうか？

2022-01-22 14:13 UTC, Oyaki122 approved these changes
LGTM!
対応いただきありがとうございました

2022-01-22 15:57 UTC, Lapis256 requested changes
Linuxで実際に実行してみたところ、動かなかったので変えたところなどを書いておきました。

2022-01-22 16:08 UTC, Lapis256 requested changes
すみません、コメントを追加し忘れていました。

2022-01-22 16:08 UTC, Lapis256 commented on README.md
>  pip install .
この前に`pip install -r requirements.txt`を実行しないと動きませんでした。

2022-01-22 16:08 UTC, Lapis256 commented on README.md
>  python run.py \
この前に`pip install -r requirements.txt`と`pip install -U numpy`を実行しないと動きませんでした。
ただ、後者に関しては、`requirements.txt`で古いバージョンの`numpy`がインストールされることで起こるエラーを解決するためのものなので、コマンドを追加するよりもバージョン指定を削除したほうがいいのではないかと思いました。

2022-01-29 09:19 UTC, Yosshi999 commented on README.md
>  python run.py \
おそらくnumpyのバージョン制限は https://github.com/VOICEVOX/voicevox_engine/pull/81 や https://github.com/VOICEVOX/voicevox_engine/issues/79 の文脈だと思うのですが、こちらではその制限は要らないかもしれませんね
この制限は0.6.0からついたもののようですが、 @Hiroshiba さん何か覚えてますか？

2022-01-29 09:39 UTC, Hiroshiba commented on README.md
>  python run.py \
そちらの制約だった気がします…！

2022-01-29 13:34 UTC, Oyaki122 requested changes
対応ありがとうございます
一点コメントしましたので確認のほどよろしくおねがいします

2022-01-29 13:34 UTC, Oyaki122 commented on README.md
> +4. `release/`内にある、自身の環境に対応したランタイムライブラリを`core/lib/`にコピーし、名前をWindowsなら`core.dll`に、linuxなら`libcore.so`に変更する。
Windows,Linuxと挙げているのであればMacについても記述したほうがいいのではないでしょうか？

2022-01-29 15:52 UTC, Yosshi999 commented on README.md
> +4. `release/`内にある、自身の環境に対応したランタイムライブラリを`core/lib/`にコピーし、名前をWindowsなら`core.dll`に、linuxなら`libcore.so`に変更する。
確かにそうですね。`libcore.dylib` であってますか？

2022-01-29 16:27 UTC, Oyaki122 commented on README.md
> +4. `release/`内にある、自身の環境に対応したランタイムライブラリを`core/lib/`にコピーし、名前をWindowsなら`core.dll`に、linuxなら`libcore.so`に変更する。
そうなんじゃないかと思いますが、申し訳ないですがMac製品を使ったことがないのでよくわかりません
どなたかわかる方いらっしゃいませんか？

2022-01-29 16:38 UTC, y-chan commented on README.md
> +4. `release/`内にある、自身の環境に対応したランタイムライブラリを`core/lib/`にコピーし、名前をWindowsなら`core.dll`に、linuxなら`libcore.so`に変更する。
`libcore.dylib`で問題ないです...!

2022-01-29 17:19 UTC, Oyaki122 approved these changes
LGTM!

2022-02-01 13:23 UTC, Hiroshiba approved these changes
LGTM！！

2022-02-01 13:23 UTC, merged