C++音声合成ライブラリの追加
VOICEVOX/voicevox_core pull request #87
Opened 2022-03-09 18:54 UTC by y-chan

## 内容

今のところ動きません
wavの生成周りは多分うまくいっていますが、それを実際に実行(https://gist.github.com/y-chan/5d09177b3771bd17bfa946623b1fd905)してみるとうまく行きません...(正しくないと思われるノイズ音声が再生されます)

## 関連 Issue

ref #43

2022-03-09 19:14 UTC, Hiroshiba commented
プルリクエスト作成ありがとうございます！！！！！
いったんみんなで実際に動かそうとしてみたり、原因を探れると嬉しいですね！！！

2022-03-09 21:58 UTC, PickledChair commented
Mac で検証してみました。ビルド・実行の過程で２点つまづいたところがあって、それを解消すると問題の「正しくないと思われるノイズ音声」が生成されました。

- Mac でビルドしてみた時に `jpcommon.h` の `FILE` が見つからないというエラーでビルドが通りませんでした。関連する以下の箇所（`core/src/engine/openjtalk.h`）で、 `#include <cstdio>` を一番先頭に持ってくるよう変更するとビルドが通るようになりました（ビルド手順のミスのせいでしたらすみません）。

https://github.com/y-chan/voicevox_core/blob/57c0902017ada63305a83b2a7baf85846cdc1010/core/src/engine/openjtalk.h#L1-L11

- そのままでは `main.cpp` のビルド結果である `a.out` の実行でコアの初期化がうまくいきませんでした。ビルド後に生成される `core/lib/` ディレクトリに `model` ディレクトリ以下にあるファイルをコピーしてから実行するとうまくいきます。

2022-03-09 22:43 UTC, Hiroshiba commented
Windowsのcl.exeで試していたのですが、LoadLibraryが突破できませんでした。。
とりあえずビルドはできたので、そこまでのメモを残してみます。

FILEが見つからないエラー　→　@PickledChair さんの方法で解決

kana_parser.cppでstd::runtime_errorが無いエラー
↓をkana_parser.cppに追記
```c++
#include <algorithm>
#include <stdexcept>
```

LoadLibraryのエラー内容は`GetLastError()`で確認できるのですが、193でした。
32bitと64bitのDLLが混在しているとエラーが出る、的な記事が見つかるのでsが、根本的にどう解決すればいいかわからずに諦めました。

2022-03-10 02:23 UTC, takana-v commented
同じくcl.exeで試してみました。
@Hiroshiba さんの方法でビルドできました。また、metas.jsonと*.onnxが必要でした。

Pythonのctypesで実行してみましたが、ヘッダー以外空のwavファイルが出力されました。
複数回ヘッダーが出現している感じです。
「テスト」で生成し再生するとバチバチといった感じの音になりました。
文字数に応じて音声ファイルの長さが変化している感じでした。
（もしかしたらctypes実装にミスがあったのかもしれません）
<details><summary>ctypes実装</summary><div>

```python
import argparse
import os
from ctypes import CDLL, POINTER, c_bool, c_char_p, c_int, c_int64, c_char
from pathlib import Path

class CppEngine:
    def __init__(self, root_dir: Path, openjtalk_dir: Path):
        self.core = CDLL(str((root_dir/"core.dll").resolve(strict=True)))

        self.core.initialize.restype = c_bool
        self.core.initialize_openjtalk.argtypes = (c_char_p,)
        self.core.initialize_openjtalk.restype = c_bool
        self.core.tts.argtypes = (c_char_p, POINTER(c_int64), POINTER(c_int))
        self.core.tts.restype = POINTER(c_char)
        cwd = os.getcwd()
        os.chdir(root_dir)
        init_core = self.core.initialize(".", False, None)
        os.chdir(cwd)
        assert init_core
        init_ojt = self.core.initialize_openjtalk(c_char_p(str(openjtalk_dir).encode()))
        assert init_ojt
    
    def tts(self, text: str, speaker_id: int):
        binary_size = POINTER(c_int)(c_int(0))
        return self.core.tts(
            c_char_p(text.encode()),
            c_int64(speaker_id),
            binary_size
        ), binary_size


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--root_dir", type=Path)
    parser.add_argument("--openjtalk_dir", type=Path)
    parser.add_argument("--text", type=str)
    parser.add_argument("--speaker_id", type=int)
    args = parser.parse_args()
    engine = CppEngine(args.root_dir, args.openjtalk_dir)
    tts_ret, bin_size = engine.tts(args.text, args.speaker_id)
    data = b""
    for i in range(bin_size.contents.value):
        data += tts_ret[i]
    
    with open("test.wav", mode="wb") as f:
        f.write(data)
```
</div></details>

![image](https://user-images.githubusercontent.com/44311840/157574778-55babffd-81fa-4f37-b011-288b9391facf.png)

2022-03-10 02:34 UTC, y-chan commented
jpcommonのためのコードを入れておいたはずが、clang-formatで移動させられて機能していなかったようです。
それと、出力される波形がおかしいのは、入力されるデータがおかしいからではないかということで、phonemeのvectorを1次元に直し、アドレスを連続させるようにしたところ、生成されるwavが改善されました。

今のところ、エラーハンドリング等まだ課題が残っているので、Draftは外さずに置いておきます。

2022-03-10 03:15 UTC, qwerty2501 requested changes
コード見てみましたが恐らく動かなくなっている原因となっているところがありました。
また随所にGCのある言語のようなノリで書かれてると思われるコードが散見されました。
C++でこれをやってしまうとメモリリークやアクセス領域違反があり大変危険な状態です。
まだあるかもしれません。

2022-03-10 03:15 UTC, qwerty2501 commented on core/src/engine/acoustic_feature_extractor.h
> +
C APIとして公開する部分以外の全てのコードに言えますが、名前競合を避けるためにnamespaceで保護したほうが良いと思います。

2022-03-10 03:15 UTC, qwerty2501 commented on core/src/engine.cpp
> +  wave_binary = wav;
これは恐らくwaveデータが無効にならないように書いたように見受けられますが、synthesis_wave_formatが呼び出された時点ですでにアクセスできない状態になっているので意味のないコードになってると思います。
そもそもstatic変数に入れてしまうと非同期アクセスに対応できないのでやめたほうがよさそうですが

2022-03-10 03:15 UTC, qwerty2501 commented on core/src/core.h
> +extern "C" VOICEVOX_CORE_API const char *tts(const char *text, int64_t *speaker_id, int *file_size);
ライブラリで公開する全てのC API関数はプロジェクト固有のprefixをつけることを強く推奨します。　たとえば `voicevox_tts` のような。
このままだとユーザー側でttsという関数が定義されていた場合関数名が競合します

2022-03-10 03:15 UTC, qwerty2501 commented on core/src/engine/openjtalk.h
> +    jpcommon = new JPCommon();
また余談ですがC++ではmemberの初期化は代入ではなく専用の構文が存在します。
https://marycore.jp/prog/cpp/initialize-data-member/#:~:text=%E3%81%AE%E5%88%9D%E6%9C%9F%E5%8C%96-,%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%AE%E3%83%A1%E3%83%B3%E3%83%90%E5%A4%89%E6%95%B0%E3%82%92%E5%88%9D%E6%9C%9F%E5%8C%96%E3%81%99%E3%82%8B%E3%81%AB%E3%81%AF,%E3%82%B3%E3%83%B3%E3%82%B9%E3%83%88%E3%83%A9%E3%82%AF%E3%82%BF%E3%82%92%E5%AE%9A%E7%BE%A9%E3%81%97%E3%81%BE%E3%81%99%E3%80%82&text=%E5%90%84%E3%83%A1%E3%83%B3%E3%83%90%E5%88%9D%E6%9C%9F%E5%8C%96%E5%AD%90,%E5%8F%AF%E8%83%BD%E3%81%A8%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82

2022-03-10 03:41 UTC, y-chan commented
> GCのある言語のようなノリで書かれてると思われるコードが散見され

おっしゃる通りと思われます。
私自身C++でコードを沢山書いたことがある訳ではなく、全くの初心者であるため、常識がわかっておらず色んな間違いがあることは否定しません。
VOICEVOXのロードマップとして、とりあえず動かせるC++ライブラリを作ると言ったことがあったので、このPRではとりあえず私の持つ既存コード(https://github.com/y-chan/node-voicevox-engine )を、Coreと結合して動かすことを目的として書き直しました。
なので、動きはするが問題が異常な程にあるといった状況に思われます。

このPRがDraftなのは、エラーハンドリング周りが完全でないことだけでなく、そういった非常識で危険なコードを修正するためでもあります。
ご指摘頂いた点はなるべく解決するようにしたいと考えています。
また、suggestionなど送っていただければ、もっと色々議論ができるかなと思います。

2022-03-10 03:56 UTC, qwerty2501 commented
@y-chan suggestionも考えたのですがちょっと広範になりそうなのでとりあえず今思ってることで良いので各コメントに対して返信していただけますか？
短くできそうなところは後でsuggestionします

2022-03-10 04:20 UTC, y-chan commented on core/src/engine/synthesis_engine.cpp
> +  return result;
これに関して、問題があるとIDEにも指摘されていましたが、どうするのが正しいのかいまいちわかっていません...
SynthesisEngineクラスに変数を作って領域を確保する等が正しいんでしょうか...

2022-03-10 04:23 UTC, y-chan commented on core/src/engine/acoustic_feature_extractor.h
> +
なるほど、確かにそうですね。
vv_engineとかって感じでnamespaceをそれぞれ確保するようにしてみます。

2022-03-10 04:25 UTC, y-chan commented on core/src/engine/openjtalk.h
> +    jpcommon = new JPCommon();
この実装はpyopenjtalkの実装の流用であるため、newしている意味があるのかと言われると私には分かりません...
newせずにそのまま代入する方が安全なのであれば、そうするようにしようかなと思います。

2022-03-10 04:28 UTC, y-chan commented on core/src/core.h
> +extern "C" VOICEVOX_CORE_API const char *tts(const char *text, int64_t *speaker_id, int *file_size);
なるほど...
たしかにprefixはあった方が良さそうです。
一旦`voicevox`をつけてみることにします。

2022-03-10 04:29 UTC, y-chan commented on core/src/engine.cpp
> +  wave_binary = wav;
ここら辺どうすればいいか私もわかっていないので、適切なやり方があれば教えて頂きたいです...

2022-03-10 06:36 UTC, Segu-g commented on core/src/engine/openjtalk.h
> +    jpcommon = new JPCommon();
pyopenjtalkではなくopnejtalkにあるopen_jtalk.cのOpen_JTalk構造体を不要な部分を除きながらclassに書き直せばいいと思います

2022-03-10 06:45 UTC, qwerty2501 commented on core/src/engine/acoustic_feature_extractor.h
> +
このリポジトリはengineではなくてcoreですのでちょっと違和感があるかもしれませんね。
vvに省略するかは任せますが、pythonのmoduleでもvoicevoxは省略してなかったのでしないほうがいいかもですね。
一案としてはこんな感じですかね？
```C++
namespace voicevox::core{
some code...
}
```

2022-03-10 07:01 UTC, y-chan commented on core/src/engine/openjtalk.h
> +    jpcommon = new JPCommon();
見てきました！
なるほど、単純に`&`を使ってポインタを渡してあげるだけで良さそうですね。
そのように書き換えてみます...!

2022-03-10 07:13 UTC, Hiroshiba commented on core/src/engine/synthesis_engine.cpp
> +  return result;
個人的には「とりあえず動く」なるべく早く目指したいと思っているので、 @y-chan さんの方法を適用するか、FIXMEコメントを付けてそのままマージするのが良いのかなと思っていいます。
マージした後に良い感じに修正していければ嬉しいです。

2022-03-10 07:16 UTC, Hiroshiba commented on core/src/core.h
> +extern "C" VOICEVOX_CORE_API const char *tts(const char *text, int64_t *speaker_id, int *file_size);
APIの形はたしかに課題ですが、マージ後させて頂いたあとにじっくり考えても良さそうです。
とりあえずなんでもOKで･･･！

2022-03-10 07:19 UTC, Hiroshiba commented
@qwerty2501 さん
レビューありがとうございます！！非常に心強いです。

戦略ですが、一旦マージしてしまえば各々がプルリクエストを送ることができるので、マージを最優先に考えています。
メモリ的に危ない箇所はたしかにありそうですが、目についたものはFIXMEコメントを付けて頂いて、多少強引ですが一旦マージしたいです･･･！

2022-03-10 07:26 UTC, Hiroshiba commented
なので、指摘箇所のうちすぐ直せる部分は直していただきつつ、難しいところはFIXMEコメントを足した状態にできればdraftを外していただければ･･･！

2022-03-10 08:00 UTC, y-chan commented on core/src/engine/openjtalk.h
> +    jpcommon = new JPCommon();
そもそもメンバの初期化が必要ないみたい([`open_jtalk.c`](https://github.com/VOICEVOX/open_jtalk/blob/1.11/src/bin/open_jtalk.c)参照)なので、初期化処理そのものを消してみました。

2022-03-10 08:34 UTC, qwerty2501 commented on core/src/engine/synthesis_engine.cpp
> +  return result;
@y-chan この関数で返してるresultはtempで保持してるheap領域のpointerです。
tempで確保してるheap領域はこの関数が終了すると解放されます。temp変数の寿命はこの関数内であるため。
ここの実装はC++であるため戻り値をpointerではなくstd::vector<uint8_t>にしてあげると解決すると思います。(waveデータはテキストではなくbyteデータのため戻り値としてはstd::stringではなくstd::vector<uint8_t>を使ったほうが望ましいです)
またその場合tempは不要になるでしょう

2022-03-10 08:42 UTC, qwerty2501 commented on core/src/engine.cpp
> +  wave_binary = wav;
呼び出されるたびにwavデータのheap領域を新しく確保したものに結果を格納して返してあげるのが良いですかね。
その場合wavデータ解放用の関数をこちらがわで定義してあげてユーザーがwaveデータを使い終わったらその関数を呼び出して開放してガ得る必要がありますが・・・
static変数に格納する実装だと仮に非同期に呼び出さなかったとしても例えば連続で2回呼び出しただけで1度目の呼び出しの結果が無効になってしまうので良くなさそうです。

2022-03-10 08:44 UTC, qwerty2501 commented on core/src/engine/openjtalk.h
> +    jpcommon = new JPCommon();
そうですね。修正後は必要ないと思います！

2022-03-10 08:49 UTC, qwerty2501 commented
コメントしましたがmergeのタイミングはお任せします

2022-03-10 08:55 UTC, Hiroshiba commented
個人的には @qwerty2501 さんにコメント頂いた２箇所を修正 or FIXMEコメント追加頂ければ一旦マージしたいですね･･･！！

2022-03-10 08:55 UTC, Segu-g commented
> 多少強引ですが一旦マージしたいです･･･！
とりあえず別ブランチとしてマージするのがいいと思います！

2022-03-10 08:57 UTC, y-chan commented
> とりあえず別ブランチとしてマージするのがいいと思います！

私もそう思いました！
exampleとかREADMEとかもまだ未整備で、テストも回ってないので、一旦別ブランチを用意して、ある程度まともになってからマージするのが良さそうだと思いました

2022-03-10 10:59 UTC, y-chan commented
とりあえず現状指摘のあった
- heapを使った方がいい(これであってるのかはわからない...)
- namespaceを使った方がいい
- prefixを付けた方がいい
と、その他のリファクタ(warningの解消やformat)を改善しました。
私たちにはwrite権限があるので、一旦cpp-libraryブランチを派生させ、PRをそちらに向けるように修正しました。

2022-03-10 11:23 UTC, qwerty2501 commented on core/src/engine.cpp
> +  memcpy(wav_heap, wav.data(), sizeof(unsigned char) * (*binary_size));
これは動作するコードです。
先程newは避けたほうが良いと指摘しましたが、この場合はnewしたほうが良いです。
newは避けるべきですが、C由来のmalloc,calloc,freeはもっと避けるべきです。(サイズ指定が煩雑で間違えやすいため)
以下のような感じに書けると思います。
```suggestion
const auto wav = engine->synthesis_wave_format(audio_query, speaker_id, binary_size);
auto* wav_heap = new uint8_t[*binary_size];
std::copy(wav.begin(),wav.end(),wav_heap);
```
考え方としては以下のように考えると良いです。
まずheap memoryを避け、stack memory上に載せられないか検討する
↓
heap memoryを使用することにした場合、vectorをメモリ領域代わりに使うか、C++のスマートポインタを使用できないか検討する
↓
Cなどの互換性のためvectorやスマートポインタを使えない場合heapメモリ確保をnew (配列)で行う。
↓
なんらかの事情でmallocやcalloc,freeを使わざるを得ない場合は使用する。

2022-03-10 11:23 UTC, qwerty2501 commented on core/src/engine.cpp
> +  free(wav);
```suggestion
  delete wav;
```
new した場合deleteに変更する必要あり

2022-03-10 11:24 UTC, qwerty2501 commented on core/src/engine/acoustic_feature_extractor.h
> +
voicevox::core::engineにしたんですね。良いと思います。

2022-03-10 11:32 UTC, qwerty2501 commented
コメントしましたがLGTMです。

2022-03-10 11:40 UTC, y-chan commented on core/src/engine.cpp
> +  memcpy(wav_heap, wav.data(), sizeof(unsigned char) * (*binary_size));
なるほど、このようなやり方があるんですね...!(`new uint8_t`と言った記述は初めて知りました)
詳しい説明ありがとうございます、参考になります...!
suggestionのコードを利用させていただきます!

2022-03-10 11:45 UTC, takana-v commented on core/src/engine.cpp
> +  accent_phrases = engine->replace_mora_data(accent_phrases, speaker_id);
```suggestion
```
create_accent_phrases内でreplace_mora_dataをしているので不要だと思われます。

2022-03-10 11:47 UTC, y-chan commented on core/src/engine.cpp
> +  accent_phrases = engine->replace_mora_data(accent_phrases, speaker_id);
本当ですね...これは私のミスです...w
suggestion利用させていただきますー!

2022-03-10 12:26 UTC, Hiroshiba approved these changes
LGTM！！！

コメント、僕もとても勉強になりました。
さすがに初手で完璧なのはなかなかなく、いろんな改善点があるかもしれません。
どんどん良くしていければ嬉しいです、プルリクエストお待ちしています！！

2022-03-10 12:27 UTC, merged