動的ライブラリにモデルファイルを同梱する
VOICEVOX/voicevox_core pull request #99
Opened 2022-03-15 13:47 UTC by Oyaki122

## 内容
#86 を実装します
https://github.com/magcks/embed を改変したcmakeスクリプトを用いて、Windowsでは.rcファイル、Mac, Linuxでは.incbin命令を用いてバイナリを埋め込む仕組みです

## 関連 Issue

ref #86 

## その他
Windows11及びWSL2 Ubuntu20.04での動作を確認しています

2022-03-17 16:46 UTC, Hiroshiba reviewed
@Yosshi999 さん、 @PickledChair さん、もしよかったらレビュー頂けるととても助かります･･･！

2022-03-19 15:15 UTC, PickledChair requested changes
ほぼ良さそうでした！（Mac でもビルドして動作確認してみましたが動きました。） 一部気になった部分にコメントしました。

また、コード外で他に２つ気になったことがあります：

- open_jtalk ディレクトリが追加されていますが、混入でしょうか？（main ブランチはまだ open_jtalk に依存していなかった気がしました）
- PR のタイトルが「静的ライブラリ」になっていますが、ビルド結果は dll なので「動的ライブラリ」が正しい？（タイトルは後でアップデート情報に記載されると思うので質問してみました）

2022-03-19 15:15 UTC, PickledChair commented on core/CMakeLists.txt
> +endif()
metas.json の存在だけを判定していますが、他の onnx ファイルについても判定しても良いのかも？ と感じました。

2022-03-19 17:05 UTC, PickledChair commented on core/src/embedBin/FindEmbed.cmake
> +	\".align ${CMAKE_SIZEOF_VOID_P}\\n\"
アセンブリに詳しくないのですが、調べたところ、`.align` は環境によって動作が異なるようです（以下の参考記事では、Windows や Linux では `.balign`, Mac や Arm 環境では `.p2align` として動作するように読めました）。手元の Mac 環境でビルド・実行した時には悪影響がなかったので変更の必要がないかもですが……（`.balign` に変更してみても期待通りに動きました）。とりあえずメモとして残しておきます。

参考：
- http://masahir0y.blogspot.com/2012/06/gas-align.html?m=1
- http://umezawa.dyndns.info/wordpress/?p=6361

2022-03-21 16:40 UTC, Yosshi999 reviewed
一件コメントしましたが、変更しなくてもかまいません！

2022-03-21 16:40 UTC, Yosshi999 commented on core/src/embedBin/FindEmbed.cmake
> +	HMODULE handle = GetModuleHandle(\"core.dll\")\;
[MAY] 本家ではここはNULLでしたが、これは `core.dll` がどうしても必要なのでしょうか？今後dllの名称が変わる可能性は低いかと思いますが、可能なら埋め込むのを避けてほしいです。

2022-03-22 05:44 UTC, Oyaki122 commented on core/CMakeLists.txt
> +endif()
修正しました

2022-03-22 06:04 UTC, Oyaki122 commented on core/src/embedBin/FindEmbed.cmake
> +	HMODULE handle = GetModuleHandle(\"core.dll\")\;
検証中、ここをNULLにしているとその後のFindResourceでリソースが見つからずエラーになりました
https://www.tokovalue.jp/function/GetModuleHandle.htm
ここによると
>NULL を指定すると、呼び出し側プロセスの作成に使われたファイルのハンドルが返る。

そうなので、呼び出し元(exampleであればpython?)のexe内から検索しようとしてしまうのだと思います

ただそのまま埋め込むのは確かに問題だと思うので、引数として渡すように変更しました

2022-03-22 06:11 UTC, Oyaki122 commented on core/src/embedBin/FindEmbed.cmake
> +	\".align ${CMAKE_SIZEOF_VOID_P}\\n\"
私もあまり理解せずに実装してしまっていて申し訳ないのです…
Macで動作しているのであれば大丈夫かと思いますが、Actionsでの検証ができないARM Linuxなどでの動作が不安なので、とりあえず.balignに変更します
問題があれば再度修正しようと思います

2022-03-22 06:12 UTC, Oyaki122 commented
レビューありがとうございます！

> 静的ライブラリ

お恥ずかしい限りです…　修正しました

> openjtalk

混入でしたので修正しました

その他の修正については各コメントにリプライしました

2022-03-22 13:21 UTC, Yosshi999 approved these changes
👍

2022-03-22 21:29 UTC, PickledChair approved these changes
LGTM！ `example/python/run.py` の引数が変更された（`--root_dir_path` がなくなった）ので、この機会に README に反映すると良いかもしれません（「[サンプル実行](https://github.com/VOICEVOX/voicevox_core#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E5%AE%9F%E8%A1%8C)」と「[コアライブラリのビルド](https://github.com/VOICEVOX/voicevox_core#%E3%82%B3%E3%82%A2%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89)」の項目に `run.py` の実行方法の記載があります）。

### メモ

今回の変更に際して考慮すべきことがありそうだったのでメモします（勘違い等ありましたらご指摘ください）。

今回の変更で、全てのOSプラットフォーム向けの共有ライブラリが１つのリソース（各 onnx ファイルと metas.json）を共有していた状態から、各共有ライブラリごとに個別にリソースが埋まっている状態に変わります。この結果、GitHub Releases で配布する `core.zip` のサイズが大きくなるはずです。共有ライブラリは 10 種類のプラットフォーム向けにビルドしていて、OSS 版コアのリソースは 60 MB 弱なので、OSS 版の場合はおよそ 600 MB で済みます。一方で製品版コアのリソースは合計で 200 MB 超あると思うので、`core.zip` のサイズは単純計算で 2 GB 超となり、GitHub Releases のファイルサイズの制限を超える可能性があります。問題ない可能性もありますが……。

考えられる対処方法：

- ZIP より圧縮率の高い圧縮方法を試す
  - 手元で 7-zip で圧縮してみた限りでは ZIP 版と大してサイズが変わらなかったので有効ではないかも
- [onnxruntime の配布方法](https://github.com/microsoft/onnxruntime/releases/tag/v1.10.0)のように、各プラットフォーム向けのバイナリごとに別々にアップロードする
  - libcore.dll, libcore.so, libcore.dylib はリネームする必要がなくなる。ただしエンジン側での読み込み方法の変更が必要となるため、互換性維持のためにリネームを続ける、という考えもありかもしれない

2022-03-23 00:02 UTC, y-chan commented
確かに、埋め込みによって色々変わりそうですし、intializeのインターフェース変更のため、エンジン側の対応(特にコアの複数バージョン対応あたり)が大変になりそうな予感です。

このPRはcpp-libraryブランチとコンフリクトしそうなので、既に発生しているmainとコンフリクトを解消する時に同時にコンフリクトを解消しようかなと思っていたのですが、一旦マージは後(エンジン等の対応がある程度できそうな目処が立ってから)にすべきかなと思いました。

2022-03-23 02:41 UTC, Hiroshiba commented
たしかに2GB超えそうですね･･･。

エンジン側の対応が必要な件は、製品版coreのプレリリースがあったほうがやりやすそうに感じました。
実際にマージしちゃったほうがビルドしやすいので、一旦マージできるとうれしいかも。
github actions環境でMac版をビルドできるかなどもチェックできると思います。
（もし未知の原因でrevertすることになった場合大変かもですが。。）

2022-03-23 12:04 UTC, PickledChair commented
ちょっと悩ましいですが、 @.Hiroshiba さんのおっしゃる通り

> エンジン側の対応が必要な件は、製品版coreのプレリリースがあったほうがやりやすそうに感じました。

というのはあると思うので、コンフリクトが小さいうちに main にマージするのが良さそうな気がしてきました。今までのペースのリリースだと色々と作業が煩雑になるリスクが高いですが、

> バージョンアップもまだ結構先になりそうですし

ということであれば、エンジン側も少し時間をかけて対応できそうです。

ということで、マージ作業をします……！

2022-03-23 12:45 UTC, PickledChair commented
x64 の Ubuntu 18.04 だけ JSON のパースに失敗してテストが落ちてますね。どうしてでしょうか……？

2022-03-23 13:34 UTC, Hiroshiba commented
本当ですね･･･きっと関係なさそうですがre runしてみます。

2022-03-23 13:38 UTC, Hiroshiba commented
エラー内容は下記らしいです。
```bash
Traceback (most recent call last):
  File "/home/runner/work/voicevox_core/voicevox_core/tests/core_test.py", line 35, in test_metas
    core.initialize(False)
  File "/home/runner/work/voicevox_core/voicevox_core/core/_core.py", line [58](https://github.com/VOICEVOX/voicevox_core/runs/5661133549?check_suite_focus=true#step:19:58), in initialize
    raise Exception(lib.last_error_message().decode())
Exception: JSON parser raise exception: [json.exception.parse_error.101] parse error at line 19, column 1: syntax error while parsing value - invalid literal; last read: '"0.0.1"<U+000A>  }<U+000A>]<U+000A>b'; expected end of input
```
最後の部分が `'"0.0.1"<U+000A>  }<U+000A>]<U+000A>b'`になってる･･･？　`b`が変なのかな･･･

ちなみに実際のmetas.jsonの最後はこんな感じです
```
    "version": "0.0.1"
  }
]
```

2022-03-23 15:00 UTC, Oyaki122 commented
このコミットでおそらく解決しています

原因は、ファイルを直接読み込んでいるためNULLポインタが末尾にあることが保証されていないにも関わらず、文字列としてjson::parseに読み込ませたことでバッファオーバーランし、たまたまメモリ上に存在した'b'を読み込んだためと思われます
そのためイテレータ用の読み込ませ方に変更しました

マージ直前にご迷惑をおかけして申し訳ありません

2022-03-23 15:10 UTC, merged